### ISSUE TITLE
Button styling

### ISSUE THREAD

**Issue by pathofleastresistor** [Nerwyn/service-call-tile-feature#10]
The current button design is something like a vertical layout (icon on top, label below). Is there a way to do a horizontal layout similar to this:

<img width="126" alt="image" src="https://github.com/Nerwyn/service-call-tile-feature/assets/91756648/5f949691-b7f4-4047-9f6b-c2073b974e20">

**Comment by renarena** [comment]
I think the same, maybe with one line of text only.
The current "vertical" icon+text version has very narrow paddings, doesnt look nice.

**Comment by Nerwyn** [comment]
The labels were an afterthought I added after it was requested very early on in the project, and were made to mimic the way Home Assistant buttons lay out icons and labels on button cards (which is admittedly not great).

Fortunately you can use the built in style options to get close to this:

```yaml
type: tile
entity: light.sunroom_ceiling
features:
  - type: custom:service-call
    entries:
      - type: button
        icon: mdi:fire
        label: Mode Heat
        style:
          flex-direction: row
        icon_style:
          left: 12px
```
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/43071698/5acbf245-d01f-4d0c-a4ca-b96edd5c7fed)

I wasn't able to get multiple lines to work though, whether I did it in yaml or manually using browser developer tools. I might be able to fix this by change the label from a `div` to `pre`

**Comment by Nerwyn** [comment]
I changed the labels to use `pre` HTML elements in [3.0.9](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/3.0.9). You can now create multi-line labels. 

```yaml
features:
  - type: custom:service-call
    entries:
      - type: button
        icon: mdi:fire
        label: |
          Mode
          Heat
        style:
          flex-direction: row
        icon_style:
          left: 8px
type: tile
entity: climate.downstairs_thermostat
```
<img alt="image" src="https://github.com/Nerwyn/service-call-tile-feature/assets/43071698/37af806c-51d6-4eb0-a79a-d8d0ec6c29ef">

You should be able to tweak it further using the style fields to modify the CSS, although you won't be able to make different parts of the text different colors or sizes since it all goes into the `pre` element text.
