### ISSUE TITLE
Inconsistent behaviour of tap action - fire dom event

### ISSUE THREAD

**Issue by BBE-FR** [Nerwyn/service-call-tile-feature#101]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
V4.3.1

**Last working release (if known):**
only tested in v4.3.0 and 4.3.1 both with same behaviour

**Browser and Operating System:**

Issue with companion app on android (pixel 7a) not tested with other devices.
No issue with browser on PC (chrome for example)

**Description of problem:**

Trying to replace my previous room card, i am experimenting with tiles and custom features. I create pop-up on some button single tap.
The fire dom event for the pop up card are working perfectly on dashboard on PC.
But **when used on mobile,** the butons that are **on the edge of the screen/section** do not work with the single tap fire dom event, all other button with same behaviour working as expected:

<img width="146" alt="Image" src="https://github.com/user-attachments/assets/657e742e-b617-4cc3-8327-e71f53e21476" />

When trying to insist with a deeper push it ether trig the hold behaviour (if specified) or raise the more info of one of the entity present in the pop-up card, or even sometimes raise the adequate pop-up card.

When using screen simulation with browser (F12 in chrome for example) everything is working fine, I only have the issue with the companion app on my pixel 7a Android phone (not tested on other devices).

When the phone is tilted, if the button is on the edge the behaviour is sometimes not consistant with reaction to the single tap but not always the pop up, sometimes a more info instead of the pop-up, but there is always a reaction (compared to vertical with no reaction to tap):
![Image](https://github.com/user-attachments/assets/8acc74f2-8176-4f35-bf7b-770b9384c348)

Swaping the card position, the "bad" behaviour is not linked with the button itself but to the position of the button on the edge of the screen / section :

![Image](https://github.com/user-attachments/assets/925d83ee-9b13-496b-9c20-899c1ee525b3)

I created a new section with 4x the same card for test purpose:
![Image](https://github.com/user-attachments/assets/cb58893f-6f89-40ba-b1b4-eae27f297acc)
Still no issue on chrome but with companion app the following affected buttons:
![Image](https://github.com/user-attachments/assets/9403cbf7-3629-4f00-aa87-c0347462935c)
![Image](https://github.com/user-attachments/assets/cf4e7035-e238-49f8-b8e9-f81b26e91d15)

**Javascript errors shown in the web inspector (if applicable):**

```
not available
```

**Your Full Card Config**
first card (salon):
```yaml
features:
  - type: custom:service-call
    entries:
      - type: button
        entity_id: group.lumieres_salon
        hold_action:
          action: toggle
          target:
            entity_id: group.lumieres_salon
          data: {}
        haptics: true
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Lumières salon
              content:
                type: custom:streamline-card
                template: pop-up-light-salon
                variables: {}
        icon: mdi:lightbulb
        color: accent
        autofill_entity_id: true
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("light.0x84ba20fffe4b2581", "on") %}
                --icon-color: orange;
                {% endif %}
          }
      - type: button
        entity_id: cover.salon
        icon: >-
          {{ iif(is_state("cover.salon", "open"), "mdi:window-shutter-open",
          "mdi:window-shutter") }}
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("cover.salon", "open") %}
                --icon-color: orange;
                {% endif %}
          }
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Volets du salon
              content:
                type: vertical-stack
                cards:
                  - type: tile
                    features_position: bottom
                    vertical: false
                    entity: cover.volet_du_salon_tv
                    name: Volet TV
                    color: accent
                    features:
                      - type: cover-open-close
                  - type: tile
                    features_position: bottom
                    vertical: false
                    entity: cover.volet_du_salon_apero
                    name: Volet Apéro
                    color: accent
                    features:
                      - type: cover-open-close
        hold_action:
          action: toggle
          target:
            entity_id: cover.salon
          data: {}
      - type: button
        entity_id: device_tracker.echo_jeanne
        icon: mdi:play-pause
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("media_player.echo_jeanne", "playing") %}
                --icon-color: blue;
                {% endif %}
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Echo salon
              content:
                type: custom:streamline-card
                template: pop-up-alexa
                variables:
                  media_player_entity_name: echo_jeanne
      - type: button
        entity_id: plant.alocatia
        icon: mdi:information
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("plant.alocatia", "alert") %}
                --icon-color: orange;
                {% endif %}
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Plante Marsupilami
              content:
                type: custom:flower-card
                entity: plant.alocatia
                show_bars:
                  - moisture
                  - temperature
                  - illuminance
                  - conductivity
                  - dli
                battery_sensor: sensor.alocasia_zebrina_battery
                display_type: compact
    styles: ""
type: tile
features_position: bottom
vertical: false
entity: sensor.tuile_salon
color: accent
icon: ""
state_content:
  - Alexa
  - Marsu
grid_options:
  columns: 6
  rows: 2
icon_hold_action:
  action: perform-action
  perform_action: light.toggle
  target:
    entity_id: light.0x84ba20fffe4b2581
icon_tap_action:
  action: perform-action
  perform_action: ""
tap_action:
  action: navigate
  navigation_path: /lovelace-smartphone/salon

```

second card : cuisine
```yaml
features:
  - type: custom:service-call
    entries:
      - type: button
        entity_id: light.led_cuisine
        hold_action:
          action: toggle
          target:
            entity_id:
              - light.led_cuisine
          data: {}
        haptics: false
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Lumière cuisine
              content:
                type: tile
                entity: light.led_cuisine
                name: LED cuisine
                features:
                  - type: toggle
                  - type: light-brightness
        icon: mdi:lightbulb
        color: accent
        autofill_entity_id: false
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("light.led_cuisine", "on") %}
                --icon-color: orange;
                {% endif %}
          }
      - type: button
        entity_id: cover.volet_cuisine
        icon: >-
          {{ iif(is_state("cover.volet_cuisine", "open"),
          "mdi:window-shutter-open", "mdi:window-shutter") }}
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("cover.volet_cuisine", "open") %}
                --icon-color: orange;
                {% endif %}
          }
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Volet de la cuisine
              content:
                type: tile
                features_position: bottom
                vertical: false
                entity: cover.volet_cuisine
                color: accent
                features:
                  - type: cover-open-close
        hold_action:
          action: toggle
          target:
            entity_id:
              - cover.volet_cuisine
          data: {}
        haptics: false
        autofill_entity_id: false
      - type: button
        entity_id: device_tracker.none_3
        icon: mdi:play-pause
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("media_player.echo_dot_jeanne", 'playing') %}
                --icon-color: blue;
                {% endif %}
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Echo cuisine
              content:
                type: custom:streamline-card
                template: pop-up-alexa
                variables:
                  media_player_entity_name: echo_dot_jeanne
        haptics: false
        autofill_entity_id: false
      - type: button
        entity_id: sensor.tuile_cuisine
        icon: mdi:information
        styles: |-
          :host {
                --icon-color: grey;
                {% if is_state("device_tracker.thermomix", "home") %}
                --icon-color: green;
                {% elif is_state("input_boolean.vaisselle_en_cours", "on") %}
                --icon-color: green;
                {% endif %}
        tap_action:
          action: fire-dom-event
          browser_mod:
            service: browser_mod.popup
            data:
              title: Info Cuisine
              content:
                type: vertical-stack
                cards:
                  - type: heading
                    heading: Cuisine
                    heading_style: subtitle
                  - type: tile
                    entity: sensor.prise_lexman_lave_vaisselle_power
                    name: Lave Vaisselle
                    icon: mdi:dishwasher
                  - type: tile
                    entity: device_tracker.thermomix
                    name: Thermomix
                    icon: mdi:blender
                  - type: heading
                    heading: Cellier
                    heading_style: subtitle
                  - type: tile
                    entity: sensor.0x94deb8fffe6e1c3f_power
                    name: Seche linge
                    icon: mdi:tumble-dryer
                  - type: tile
                    entity: sensor.0x94deb8fffe6e2623_power
                    name: Lave Linge
                    icon: mdi:washing-machine
        haptics: false
        autofill_entity_id: false
    styles: ""
type: tile
features_position: bottom
vertical: false
entity: sensor.tuile_cuisine
color: accent
icon: ""
grid_options:
  columns: 6
  rows: 2
icon_hold_action:
  action: perform-action
  perform_action: light.toggle
  target:
    entity_id: light.led_cuisine
  data: {}
icon_tap_action:
  action: perform-action
  perform_action: ""
tap_action:
  action: navigate
  navigation_path: /lovelace-smartphone/cuisine
state_content: Alexa

```
**Additional information:**
