### ISSUE TITLE
Button using service hassio.addon_restart does not work due to entity_id

### ISSUE THREAD

**Issue by renarena** [Nerwyn/service-call-tile-feature#11]
**Release with the issue:**
3.0.5

**Browser and Operating System:**
Firefox 120 on linux/LMDE6

I try to restart an addon (ssh as example) using Button.

This gives "extra keys not allowed @ data['entity_id']"
If i use` autofill_entity_id: false`  the button disappears.

```yaml
  - type: custom:service-call
    entries:
      - type: button
        icon: mdi:reload
        label: Restart Addon
        service: hassio.addon_restart
        data:
          addon: a0d7b954_ssh
```

**Additional information:**
