### ISSUE TITLE
Slider not showing correctly on Android Companion app

### ISSUE THREAD

**Issue by vincentkoevoets** [Nerwyn/service-call-tile-feature#119]
**Checklist:**

- [ x ] I updated to the latest version available
- [ x ] I cleared the cache of my browser
- [ x ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.4.1
**Last working release (if known):**
Unknown
**Browser and Operating System:**
Latest Android companion app, but also Fully Kiosk browser. Normal browser does not have this problem. 

**Description of problem:**
The android companion app does not show slider correctly. It should show 20%, so slider almost empty. But instead it shows a full red slider. It is red, so that indicates the state is correctly read (I think). 

**Javascript errors shown in the web inspector (if applicable):**
Found an error in the logs about webview: 
```
Uncaught error from Chrome WebView 137.0.7151.23 on Android 11 Script error. null @:0:0
```
**Your Full Card Config**

```yaml
features:
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: sensor.cph2493_vincent_battery_level
        range:
          - 0
          - 100
        tap_action:
          action: none
        step: 1
        thumb: flat
        label: "{{ value | int }}%"
        autofill_entity_id: false
type: tile
entity: sensor.cph2493_vincent_battery_level
features_position: inline
vertical: false
name: Telefoon Vincent
tap_action:
  action: none
hide_state: true
grid_options:
  columns: 12
  rows: auto


```

**Additional information:**
I tried all of the things mentioned in the issue template, but none of them seem to work. I would really like to use the companion app, because something like chrome or firefox might be overkill for my relatively old tablet. 
That said, I think this might be an issue with android webview, because that is what the companion app and Fully Kiosk both use. I tried to replace webview for the beta version, but with the same results. 
If more data is needed, please let me know. 

Edit:
Well that's strange.. The same sliders show up just fine on the companion app on my phone. So maybe it's the android version on the tablet? 
Will investigate further. 

Companion app: 
![Image](https://github.com/user-attachments/assets/7c442ae4-a60e-40b9-b4a2-2e58bc800ffd)

Normal browser:
![Image](https://github.com/user-attachments/assets/fb120670-80ef-42a4-bbf9-522acc9abd15)
