### ISSUE TITLE
ugly slider in FIrefox

### ISSUE THREAD

**Issue by renarena** [Nerwyn/service-call-tile-feature#12]
**Release with the issue:** 3.0.5
**Browser and Operating System:** Firefox 120, Linux/LMDE6

**Description of problem:** The slider doesnt look as nice as the original one. 
Could you maybe use same html/css as native sliders?

```yaml
 - type: numeric-input
    style: slider
  - type: custom:service-call
    entries:
      - type: slider
        service: input_number.set_value
        entity: input_number.batterie_high
        data:
          value: VALUE
```

**Additional information:**
