### ISSUE TITLE
perform-action on a Toggle custom-feature

### ISSUE THREAD

**Issue by mmbarki** [Nerwyn/service-call-tile-feature#120]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**

**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
When using a "toggle" custom-feature , the only action that seems to be executed is the default toggle behavior. However, the UI and documentation suggest that it should be possible to set a different tap_action.

For example:

```
features:
  - type: custom:service-call
    entries:
      - type: toggle
        tap_action:
          action: perform-action
          perform_action: light.turn_on
          target:
            entity_id:
              - light.light_bureau
```

I used "light.turn_on" as an example, but in my case I actually want to execute a script that simulates a toggle on a lock (lock/unlock), like this:

```
features:
  - type: custom:service-call
    entries:
      - type: toggle
        tap_action:
          action: perform-action
          perform_action: script.toggle_lock
          data:
            lock_entity: lock.porte_d_entree_nk
```

setting `tap_action: perform-action` does nothing. This gives the impression that tap_action is configurable, but in reality, it is not working for other actions.
Of course, I can use a button instead of the toggle, and in fact I tested the same code with my `toggle_lock` script and it works perfectly. However, I prefer the visual appearance of the toggle.

![Image](https://github.com/user-attachments/assets/4ab7fd0e-585d-41f3-bd37-a307af316ee5)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Card Config**

```
type: tile
entity: lock.porte_d_entree_nk
features_position: inline
vertical: false
name: Appartement
grid_options:
  columns: full
  rows: 1
state_content:
  - state
  - last_changed
features:
  - type: custom:service-call
    entries:
      - type: toggle
        tap_action:
          action: perform-action
          perform_action: script.toggle_lock
          target:
            entity_id: lock.porte_d_entree_nk
          data:
            lock_entity: lock.porte_d_entree_nk
        swipe_only: true
        unchecked_icon: mdi:lock-open-variant
        checked_icon: mdi:lock
        checked_values:
          - locked
        full_swipe: false
        haptics: false
        allow_list: true
        check_numeric: false
        icon: ""
        thumb: md3-switch
        label: " "
        autofill_entity_id: true
        entity_id: lock.porte_d_entree_nk

```

**Additional information:**
