### ISSUE TITLE
Add more examples for using button, slider, selector and so on to documentation

### ISSUE THREAD

**Issue by renarena** [Nerwyn/service-call-tile-feature#13]
There is no simple but complete example i can copy/paste from, especially as there is no UI and no default yaml code..

It would be nice to have some “full” examples per feature type. 
I had to read the HA thread and the readme several times to put it together, as the examples are very complex, omit default values and f.e. input_numbers.

Thats something i miss in a lot of HA documentation.
Most have a minimum yaml example, but not one including all options, which you can copy/paste and delete lines you dont need rather then picking all the options out of several tables.

**Describe the solution you'd like**
Add minimal and full examples to documentation like this 
```
      - type: slider
        service: input_number.set_value
        entity_id: input_number.number
        range:
          - '{{ state_attr("input_number.number", "min") }}'
          - '{{ state_attr("input_number.number", "max") }}'
        step: '{{ state_attr("input_number.number", "step") }}'
```
Add similar code as default on adding the service call feature to tile card, so users have something to start with.

Maybe add also examples how i can style a button or add an ability to use the respective entities default attributes (icon, color, ...) to show f.e. if a switch is on or off .
