### ISSUE TITLE
Use min/max/step attributes of input_numbers as default values for range/step

### ISSUE THREAD

**Issue by renarena** [Nerwyn/service-call-tile-feature#14]
Use min/max/step attributes of entity_id: input_number (if any) as default values for range/step.

So one dont have to write
```
      - type: slider
        service: input_number.set_value
        entity_id: input_number.number
        range:
          - '{{ state_attr("input_number.number", "min") }}'
          - '{{ state_attr("input_number.number", "max") }}'
        step: '{{ state_attr("input_number.number", "step") }}'
```
