### ISSUE TITLE
Show the current value when moving a slider

### ISSUE THREAD

**Issue by renarena** [Nerwyn/service-call-tile-feature#15]
Its difficult to move the slider to the correct position without this :-)
Maybe you can use the code of the native slider?

**Comment by Nerwyn** [comment]
Because of how lit re-renders elements when a property (like the hass object) changes, implementing this has proven very difficult. I'm going to have to shelve attempts on this for a very slow day.

**Comment by Nerwyn** [comment]
@renarena it took a lot of changes but I think I've got it working well in [3.1.9-beta.001](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/3.1.9-beta.001) if y'all could give it a try.

**Comment by Xlinx64** [comment]
Hi @Nerwyn!
I tried the beta but there is no value shown when I move it. Do I have to configure something?
```
type: custom:service-call
entries:
  - type: slider
    range:
      - 5
      - 30
    step: 0,5
    tap_action:
      action: call-service
      service: climate.set_temperature
      target:
        entity_id: climate.hmip_wth_1_003920c994f70a
      data:
        temperature: VALUE
```
Firefox 123.0.1 on MacOS 14.3.1

**Comment by renarena** [comment]
It does not work

**Comment by Nerwyn** [comment]
You have to include `VALUE` in the label.

I should probably work on adding a tooltip too.

**Comment by Xlinx64** [comment]
It kinda works, but with cllimate entities it is a weird edge case since the state is not value to be set. So it says heat until you move the slider. See screenshots:
![IMG_4922](https://github.com/Nerwyn/service-call-tile-feature/assets/14150988/42b810b0-cca7-4550-8e85-11272b5ea9f5)


![IMG_4923](https://github.com/Nerwyn/service-call-tile-feature/assets/14150988/56db616e-aaec-4de0-92b3-eeb9e479ca59)

**Comment by Nerwyn** [comment]
You have to set `value_attribute` to `temperature`

```yaml
type: custom:service-call
entries:
  - type: slider
    service: climate.set_temperature
    value_attribute: temperature
    label: VALUE
    range:
      - '{{ state_attr("climate.downstairs_thermostat", "min_temp") }}'
      - '{{ state_attr("climate.downstairs_thermostat", "max_temp") }}'
    tap_action:
      data:
        entity_id: climate.downstairs_thermostat
        temperature: VALUE
```

**Comment by Nerwyn** [comment]
Good news - I got an alpha version of the tooltip working in Home Assistant. I still need to figure out how to make it track the slider thumb and fix it's style to match the native slider tooltip style.

**Comment by Xlinx64** [comment]
Wow, you are fast. Thank you. Can’t wait to look at this feature.

I just wanted to write that I have a perfect setup now. I just have to look into styling to increase the font size a little. I used a different “thumb” to to not cover the value.

![IMG_4927](https://github.com/Nerwyn/service-call-tile-feature/assets/14150988/6c9a17d5-923b-4fba-a6ed-7fe9827a23fd)

**Comment by Nerwyn** [comment]
I lost my job a few weeks ago so I have a lot of free time 😐. In case y'all know anyone who needs a backend or fullstack Python or TypeScript developer.

**Comment by Xlinx64** [comment]
Sorry to hear, where are you located?
I work at [Ebcont](https://www.ebcont.com/en) and we are always searching for people. We are based in Austria. I think we have 2 offices in the US but I don’t know if we have fully remote work.(It’s a tax thing)

PS: Nevertheless, thank you for your work on this awesome project. I sent some coffee your way.

**Comment by Nerwyn** [comment]
I'm in the US on the east coast. I've been remote most of my career (5/6.5 years) and wouldn't want to work in office or hybrid unless I was very desperate and out of money. Thanks for the coffees! I think I should have the tooltip fully working in beta later tonight.

**Comment by Nerwyn** [comment]
Alright, the latest beta has a fully working tooltip. Moves with the slider thumb and has user set units and everything.
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/43071698/54f52686-a04c-4734-87ac-61fe4a026a73)
Let me know how it works for y'all! I've tested it successfully on Brave, Firefox, and the Android and iPhone HA apps.

**Comment by Nerwyn** [comment]
Also to increase the font size add this to your slider config:
```yaml
label_style:
  font-size: 16px
```

**Comment by Nerwyn** [comment]
Here's the CSS for the tooltip. It uses the same background and color values as the native slider tooltips so it should be the same?

```css
.tooltip {
  z-index: 3;
  background: var(--clear-background-color);
  color: var(--primary-text-color);
  position: absolute;
  border-radius: 0.8em;
  padding: 0.2em 0.4em;
  height: 20px;
  width: fit-content;
  line-height: 20px;
  top: -29px;
  transform: translateX(var(--x-position));
  --x-position: 0px;
}
```

I'll have to implement some more robust logic for determining whether or not to remove the trailing .0 decimal. As it is now it gets removed because some services fail if you give it a float instead of an integer.

I'm also going to have to take another look at the firefox flat thumb slider css since I see another visual bug in your videos.
