### ISSUE TITLE
Button gets triggered accidentally when swiping for scrolling on mobile

### ISSUE THREAD

**Issue by Feuerhamster** [Nerwyn/service-call-tile-feature#16]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** Current

**Last working release (if known):** /

**Browser and Operating System:**
Android 13 with HomeAssistant App

**Description of problem:**

Tile card feature buttons are getting triggered by accident when swiping to scroll.
I posted a video showing the issue: https://youtu.be/fRQNLYEdWv4.
The button should only be triggered if actually pressed. I guess there is something wrong with the event listeners on the button.

**Javascript errors shown in the web inspector (if applicable):** /

**YAML of tile card:**

```yaml
features:
  - type: custom:service-call
    entries:
      - type: button
        icon: mdi:power
        tap_action:
          action: call-service
          service: switch.toggle
          target:
            entity_id: switch.fernsehbank_steckdosenleiste_schalter
type: tile
entity: switch.fernsehbank_steckdosenleiste_schalter
name: TV Bank
icon: mdi:power-socket-eu
state_content: state
vertical: false
show_entity_picture: false

```
