### ISSUE TITLE
Button Edges Not Vertically Aligned with Default Tile Features

### ISSUE THREAD

**Issue by Nerwyn** [Nerwyn/service-call-tile-feature#2]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
v1.1.0

**Last working release (if known):**
NA

**Browser and Operating System:**
Windows 10 / Brave, Android / HA app

**Description of problem:**
Margins on edges are too large and do not match HA native tile features

**Javascript errors shown in the web inspector (if applicable):**

```
NA
```

**Your Full Remote Config**

```yaml
features:
  - type: fan-speed
  - type: custom:service-call
    buttons:
      - service: fan.decrease_speed
        icon: mdi:fan-chevron-down
      - service: fan.increase_speed
        icon: mdi:fan-chevron-up
type: tile
entity: fan.lounge_ceiling
name: Ceiling Fan
vertical: false
card_mod:
  style:
    hui-tile-features$:
      hui-fan-speed-tile-feature$: |
        ha-control-select {
          {% if is_state("fan.lounge_ceiling", "off") %}
          --control-select-color: #484a4e !important;
          {% endif %}
          --control-select-background: #050505 !important;
        }

```
<img width="410" alt="image" src="https://github.com/Nerwyn/service-call-tile-feature/assets/43071698/1676b0d0-83c8-4e99-b0b9-3ebbda859044">

**Additional information:**
Current CSS margin was set to match the width between cover buttons. This margin is fine for the space between buttons but not the edge between the first/last button and the edges of the tile card.
