### ISSUE TITLE
Can't create card

### ISSUE THREAD

**Issue by wirecuttr** [Nerwyn/service-call-tile-feature#3]
Hi, Not sure what I'm doing wrong. I installed the card through HACS. When I create a tile card and go to the code view and start with the example, I just get an error:
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/3d995de4-db69-4854-badd-ed429ecd15b7)

Any idean?

**Comment by Nerwyn** [comment]
You're using it wrong. You need to create a tile card, and then add `Service Call` tile features to it.
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/43071698/5518db95-2499-4f4e-80a2-89f025103e01)

**Comment by wirecuttr** [comment]
So I did start with a Tile care and switched to the code editor because I can't add any features. 
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/4799fc63-59c2-47c2-8a61-8829b9d38a85)


I tried many different entities and still no Add Feature button appears.

The service I'm trying to call is:
'''
service: emporia_vue.set_charger_current
data:
  current: 8
target:
  entity_id: switch.ev_charger
'''

My HA version is:
Core
2023.11.0
Frontend
20231030.1

**Comment by Nerwyn** [comment]
Well that's not good. Did you try clearing cache? Can you open your browsers developer tools (CTRL + Shift + I on chromium based browsers) and see if any errors show up in the log?

**Comment by wirecuttr** [comment]
So clearing the cache actually seems to have fixed the missing Add Feature button!

Having trouble getting a slider to work still.
I am able to create a slider:
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/9182a6db-e7b2-45d9-9a98-4e6441c6e2d7)

but when I move the slider I get this error pop up from the bottom left of the screen:
```
Failed to call service emporia_vue/set_charger_current. 'NoneType' object has no attribute 'unique_id'
```

The service call details are usually:
```
service: emporia_vue.set_charger_current
data:
  current: 8
target:
  entity_id: switch.ev_charger
```

The device attributes are::
charging_rate: 32
max_charging_rate: 48
status: Standby
message: Connected to EV
fault_text: null
device_class: outlet
friendly_name: EV Charger

Any idea what I'm doing wrong?

**Comment by Nerwyn** [comment]
I'm not familiar with this integration. Could you try making this service call with the Home Assistant service developer tool and post the YAML you get from that here?

**Comment by Nerwyn** [comment]
Could you also check your Home Assistant logs and see if there's more information about the error there?

**Comment by Nerwyn** [comment]
I got curious and dug around the emporia vue source code and found [this](https://github.com/magico13/ha-emporia-vue/blob/master/custom_components/emporia_vue/__init__.py#L215C9-L243C56):

Could you try making `entity_id` an array with `switch.ev_charger` and the only item in it?

**Comment by wirecuttr** [comment]
I've created a regular button card and it works fine:
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/1ca54f4d-aa12-4abd-b309-3de7453632c5)

Also this automation works fine:
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/be39bd87-c2da-461f-acd5-7644ed821534)

The logs don't show anything about the error that I could fine.

**Comment by wirecuttr** [comment]
> I got curious and dug around the emporia vue source code and found [this](https://github.com/magico13/ha-emporia-vue/blob/master/custom_components/emporia_vue/__init__.py#L215C9-L243C56):
> 
> Could you try making `entity_id` an array with `switch.ev_charger` and the only item in it?

I'm not sure how to do this....?

**Comment by Nerwyn** [comment]
Like this:
```yaml
target:
  entity_id:
    - switch.ev_charger
```
Although if it's working with the button I'm not sure if it'll make a difference.

**Comment by Nerwyn** [comment]
From what I see in the emporia vue code it gets `charger_entity` from the `entity_registry` based on the device or entity ID the user provides, but for some reason when you call this service using a custom tile feature `charger_entity` is `None` when it tries to check it's `unique_id`. I wonder if this is due to the `charger_entity` not being set yet since it uses `async_get`. I'm not sure why this wouldn't happen for native Home Assistant buttons and automations though if that were the case.

**Comment by wirecuttr** [comment]
So if I ch

> Like this:
> 
> ```yaml
> target:
>   entity_id:
>     - switch.ev_charger
> ```
> 
> Although if it's working with the button I'm not sure if it'll make a difference.

When I do this:
```
features:
  - type: custom:service-call
    entries:
      - type: slider
        icon: mdi:ev-station
        service: emporia_vue.set_charger_current
        target:
          entity_id:
            - switch.ev_charger
        range:
          - 6
          - 48
        step: 1
        value_attribute: charging_rate
        thumb: default
        label: ATTRIBUTE[charging_rate] A
        data:
          current: VALUE
          entity_id: switch.ev_charger
```

 I get a different error:
```
Failed to call service emporia_vue/set_charger_current. '>' not between instances of 'str' and 'int'
```

**Comment by Nerwyn** [comment]
Can you try again but remove `entity-id` from data? You have it listed twice.

**Comment by wirecuttr** [comment]
changed to:
```
features:
  - type: custom:service-call
    entries:
      - type: slider
        icon: mdi:ev-station
        service: emporia_vue.set_charger_current
        target:
          entity_id: switch.ev_charger
        range:
          - 6
          - 48
        step: 1
        value_attribute: charging_rate
        thumb: default
        label: ATTRIBUTE[charging_rate] A
        data:
          current: VALUE
```

no change in the behaviour. I still get:
```
Failed to call service emporia_vue/set_charger_current. 'NoneType' object has no attribute 'unique_id'
```

**Comment by Nerwyn** [comment]
Because of that error I think it's a weird async race condition bug in the emporia vue integration. Looking through the code where I think this is being thrown:

```python
charger_entity = None
if device_id:
    entity_registry = er.async_get(hass)
    entities = er.async_entries_for_device(entity_registry, device_id[0])
    for entity in entities:
        _LOGGER.info("Entity is %s", str(entity))
        if entity.entity_id.startswith("switch"):
            charger_entity = entity
            break
    if not charger_entity:
        charger_entity = entities[0]
elif entity_id:
    entity_registry = er.async_get(hass)
    charger_entity = entity_registry.async_get(entity_id[0])
if not charger_entity:
    raise HomeAssistantError("Target device or Entity required.")

unique_entity_id = charger_entity.unique_id
```
Because you are providing the entity ID, it should hit the `elif entity_id` block and not throw the `Target device or Entity required.` error. Because the entity registry get call is async, it has not completed execution by the time the code tries to access it. I'd share this bug with the developer of emporia vue. [Home Assistant's developer documentation has a page on calling async functions that can be a useful read](https://developers.home-assistant.io/docs/asyncio_working_with_async/#calling-async-functions-from-threads)

**Comment by wirecuttr** [comment]
Thanks. Will raise an issue on that end and see what he thinks

**Comment by Nerwyn** [comment]
Based on what @magico13 found out I've added some logic to prevent slider values from being cast to string if the data key value is just `VALUE`.

https://github.com/Nerwyn/service-call-tile-feature/releases/tag/v2.0.4

Let me know if this fixes your issue!

**Comment by wirecuttr** [comment]
I got the slider to work now. 
I tried creating some buttons and still get the error when using buttons. I've tried defining the buttons two ways as show below.

![Screenshot from 2023-11-07 18-36-13](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/77c0db04-8aee-40ed-ab8f-ccc4a1262ce8)

and 

![Screenshot from 2023-11-07 18-38-41](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/8c1fecc4-6a52-49b1-a07a-1688cf81b9ba)


In both cases I get the same error:
```
Failed to call service emporia_vue/set_charger_current. 'NoneType' object has no attribute 'unique_id'
```

Any idea?

**Comment by magico13** [comment]
You might still need the target block, I think right now the entity info isn't being sent on the service call. On the ha-emporia-vue side I can probably tweak that to have a better error message.

**Comment by Nerwyn** [comment]
It should copy the feature entity ID (and if that's not present the tile card entity ID) if no entity, device, or area ID is provided in the service call data. And vice versa if a service call entity ID is provided but not a feature entity ID. It's working for me on the latest version. I also double checked the code and it shouldn't be doing any weird typecasting one the data values like before.

**Comment by wirecuttr** [comment]
Adding the target block fixed it for me.

This card config works fine. I've defined buttons both ways and they both work with the target block:

```
features:
  - type: custom:service-call
    entries:
      - type: slider
        icon: mdi:ev-station
        service: emporia_vue.set_charger_current
        target:
          entity_id:
            - switch.ev_charger
        range:
          - 6
          - 48
        step: 1
        value_attribute: charging_rate
        thumb: default
        label: ATTRIBUTE[charging_rate] A
        data:
          current: VALUE
  - type: custom:service-call
    buttons:
      - service: emporia_vue.set_charger_current
        color: aqua
        label: 6 A (1.4 kW)
        label_color: white
        target:
          entity_id:
            - switch.ev_charger
        data:
          current: 6
      - service: emporia_vue.set_charger_current
        color: cyan
        label: 15 A (3.6 kW)
        label_color: white
        target:
          entity_id:
            - switch.ev_charger
        data:
          current: 15
      - service: emporia_vue.set_charger_current
        color: cyan
        label: 24 A (5.8 kW)
        label_color: white
        target:
          entity_id:
            - switch.ev_charger
        data:
          current: 24
  - type: custom:service-call
    entries:
      - type: button
        service: emporia_vue.set_charger_current
        color: aqua
        label: 35 A (8.4 kW)
        label_color: white
        target:
          entity_id:
            - switch.ev_charger
        data:
          current: 35
      - type: button
        service: emporia_vue.set_charger_current
        color: aqua
        label: 40 A (9.9 kW)
        label_color: coral
        target:
          entity_id:
            - switch.ev_charger
        data:
          current: 40
      - type: button
        service: emporia_vue.set_charger_current
        color: aqua
        label: 48 A (11.5 kW)
        label_color: coral
        target:
          entity_id:
            - switch.ev_charger
        data:
          current: 40
type: tile
entity: switch.ev_charger
icon_tap_action:
  action: toggle

```

![image](https://github.com/Nerwyn/service-call-tile-feature/assets/40327874/71b7fa69-bb31-4be0-86be-47c1396ff8e8)
