### ISSUE TITLE
Slider not working on iOS

### ISSUE THREAD

**Issue by PepijnVG** [Nerwyn/service-call-tile-feature#30]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:** 3.3.7

**Last working release (if known):** unknown

**Browser and Operating System:**
iOS:  17.5.1
HA Companion App: 2024.5.1

**Description of problem:**
I have a tile for my curtain that contains a slider to specify the percentage to open/close my curtain to. This slider calls a script which then performs some checks and then opens/closes the curtain. Now in any web-browser (including safari on iOS) this works perfectly, however in the companion app of HA the slider doesn't want to move when I try to and the induced script gets passed an empty string ('') instead of a number as a string (e.g. '73'). This empty string understandably makes my script crash as it tries to change the string to an int.

**Your Full Tile Config**

```yaml
features:
  - type: custom:service-call
    entries:
      - type: slider
        icon: mdi:curtains
        entity_id: cover.curtain_bedroom
        value_attribute: current_position
        tap_action:
          action: call-service
          service: script.close_curtains
          data:
            input:
              - Bedroom
              - '{{ value }}'
type: tile
name: Curtains
entity: input_select.curtain_select
show_entity_picture: false
vertical: false
```

**Additional information:**
