### ISSUE TITLE
'Misaligned' icon sizes

### ISSUE THREAD

**Issue by Tamas-Toth-ebola** [Nerwyn/service-call-tile-feature#32]
**Checklist:**

- [x ] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**

4.0.0-beta.001 _(but I think the 'problem' is version independent)_

**Last working release (if known):**

I think the 'problem' is version independent

**Browser and Operating System:**

Official Ubuntu 24.04 Desktop + Chrome 126.0.6478.126 _(Official Build) (64-bit)_

**Description of problem:**

First of all, I would like to thank you very much for this fantastic plugin! This should be official feature, as your description write.

The problem is a very small barely visible problem, I had just caught it today, totally random. If you check my screenshot, the last 2 rows, the first one is the official HVAC fam-mode row, the second one is my custom with an addition button, to silent mode. **So if you check the 2 rows your icons are a bit larger than the official tile button icons.**

I just report it for the global consistency, of course, this is really a very minor problem.

![image](https://github.com/Nerwyn/service-call-tile-feature/assets/25765137/ffa20d64-53bf-4361-a343-b8a7283881cd)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml

```

**Additional information:**

**Comment by Tamas-Toth-ebola** [comment]
Also the button hover style behaviour is not the same as the official. The official buttons - on hover - have a very slight opacity of the active tile button color, while your buttons have a very-light-grey color on hover.

**Comment by Nerwyn** [comment]
Nice attention to detail! I hadn't noticed either of those. the buttons also use the 20x20px icon size, so I should make that the default for `--mdc-icon-size`.

I should also be able to copy the ripple color variables from the built in tile features and use them with mwc-ripple.

**Comment by Nerwyn** [comment]
Fixing the ripples may take some more time, as `ha-ripple` seems to have more logic for fixing the ripple after pressing the button while the ripple remains stuck for mwc-ripple.

**Comment by Nerwyn** [comment]
@Tamas-Toth-ebola can you try the latest v4 beta? I was able to switch to the material/web ripple and it seems to be performing like the built in features.

**Comment by Tamas-Toth-ebola** [comment]
Hi!

With beta.003 I get the following...

Official buttons...

![image](https://github.com/Nerwyn/service-call-tile-feature/assets/25765137/63fd861c-7350-4803-a47e-34f734862c2f)

Your buttons...
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/25765137/64314073-92ec-4605-8e34-f53bbce9a749)

The second button is where my mouse pointer was, just not grabbed.

Grey vs. light-title-color

**Comment by Nerwyn** [comment]
I think you may need to clear browser cache. I'm getting the smaller icons and correct overlay color.
![image](https://github.com/Nerwyn/service-call-tile-feature/assets/43071698/f9482b02-31e2-4ca2-8497-2d0381010aab)

**Comment by Tamas-Toth-ebola** [comment]
Hi @Nerwyn !

You were basically right, but in a strange way :smile: 

'Of course' I already originally refreshed my browser enough time to clear it's cache, but there were an interesting detail... While I used the latest beta, I still did not get the GUI based functions. Now I re-downloaded the plugin from HACS, as option of HACS, and seems, with it... the plugin totally refreshed as I finally have gotten the GUI functions and the refreshed styles.

But this is just a half success, as the icon sizes seem really solved, but the hover effect is interesting.

I previously used the following style definitions _(I mean, for example)_...

```yaml
            style:
              '--color': |
                {% if state_attr('climate.climate', 'fan_mode') == 'auto' %}
                  var(--tile-color)
                {% else %}
                  initial
                {% endif %}
              '--opacity': |
                {% if state_attr('climate.climate', 'fan_mode') == 'auto' %}
                  1
                {% else %}
                  0
                {% endif %}     
              '--icon-color': |
                {% if state_attr('climate.climate', 'fan_mode') == 'auto' %}
                  var(--white-color)
                {% else %}
                  initial
                {% endif %}
```

...because, without it, I do not get proper state reporting, so the 'buttons' do not follow the state of the entity/attribute behind it. Also the original HA buttons have inverted icons if the buttons are active, to keep the contrast with the colored buttons. Your buttons have only one icon color without the custom 'hack', so I did it...

As the GUI based functions make sterile new configs, the result is a proper hover style on the buttons, but how can I use the state of the entities behind them to drive the button states?

Also interesting that the written lines are true for 'selectors', but plain buttons do not have correct hover styles, at least for me, never...

**Lot of thank for your fast response, effort, and for all! You are really a star with this functions... should be PR-ed into the official codebase.**

**Comment by Tamas-Toth-ebola** [comment]
Just one another sentence...

I forgot, why I had searched for custom solution for proper button colorization...

With your official attribute (`value_attribute`) I simply could not get the proper result...

For the selector entry earlier I tried the following...

```yaml
        entity_id: climate.climate
        value_attribute: fan_mode
```
...but sadly without properly selected active button.

My HVAC has the following attributes and results _(example)_...

```yaml
hvac_modes: auto, cool, dry, fan_only, heat, off
min_temp: 8
max_temp: 30
target_temp_step: 1
fan_modes: auto, low, medium low, medium, medium high, high
preset_modes: eco, away, boost, none, sleep
swing_modes: off, vertical, horizontal, both
current_temperature: 25
temperature: 25
fan_mode: low
preset_mode: none
swing_mode: off
friendly_name: [Climate]
supported_features: 441
```

Where do I make a mistake? _(Sorry I totally forgot, that this was the reason why I made the custom button styles...)_

**Comment by Nerwyn** [comment]
You should be setting the `option` field of each option button to the fan mode attribute value you want in order for it to highlight based on the selector attribute value with no additional styles needed. Something like this:

```yaml
options:
  - option: auto
    icon: mdi:fan-auto
  - option: low
    icon: mdi:speedometer-slow
  - option: medium low
    icon: mdi:circle-medium
  - option: medium
    icon: mdi:speedometer-medium
  - option: medium high
    icon: mdi:circle-medium
  - option: high
    icon: mdi:speedometer
```
