### ISSUE TITLE
Allow tile card to automatically resize for hidden "features" due to state

### ISSUE THREAD

**Issue by irakhlin** [Nerwyn/service-call-tile-feature#33]
**Is your feature request related to a problem? Please describe.**
The "show"/"hide" feature you have is a game changer for me when it comes to the tile card, as its not available on any of the default features for tile card. The only addition I believe would be great is providing an option to allow the card to "resize" its size based on the current visible "features". For example in the screenshots I have below, I have a light with a brightness slider that is only shown when the light is on, however when the light is off the card space where the slider would be displayed is still used by the card. Allowing the card to resize due to what is shown/hidden could make for a more compact mobile UI.

**Describe the solution you'd like**
If this is possible it may make sense to allow for an option like "allow_resize" at the same level as the "show" and "hide" options, that could be set to true/false. 

**Describe alternatives you've considered**
It seems that making the tile card part of a nested horizontal card achieves the same result, however with the new "Sections" view and ability to resize cards I was hoping to avoid using these for a more robust layout.

**Additional context**
In the following two screenshots the yaml for "Dining Room Lights" at the top and bottom are identical, the only difference is the top "Dining Room Lights" is nested in a horizontal stack. As you can see when the light is off and the brightness bar is hidden the card automatically resizes to its minimal size. I am assuming this must be due to something the horizontal stack card is doing as the bottom example of just the tile card on its own does not have this behavior.

Light off:
![example1](https://github.com/Nerwyn/service-call-tile-feature/assets/12637936/d872bad2-416c-4fc9-9377-4003896e3baf)

Light on:
![example2](https://github.com/Nerwyn/service-call-tile-feature/assets/12637936/ba35e7a5-839d-419c-9ea9-c5080b54a927)

For reference the yaml for the "Dining Room lights" card is the following:
```yaml
features:
  - type: custom:service-call
    show: '{{ is_state("light.dining_room_light", "on") }}'
    hide: '{{ is_state("light.dining_room_light", "off") }}'
    entries:
      - type: slider
        label: VALUE
        thumb: flat
        unit_of_measurement: '%'
        value_attribute: brightness
        tap_action:
          action: call-service
          service: light.turn_on
          data:
            brightness_pct: VALUE
            entity_id: light.dining_room_light
type: tile
entity: light.dining_room_light
tap_action:
  action: toggle
```

**Comment by Nerwyn** [comment]
Card sizing is handled by Home Assistant, with only the minimum card size being defined by the features themselves. The tiles taking up the full size in section view is actually a problem with how section view forces tiles into at least two rows, even if they have one or no features. I spent last night wrestling with this to upgrade my dashboard to use sections.

There is a hidden feature/hack with section view layouts that allows you to force rows to conform to minimum card height. Set `layout_options.grid_rows` to a non-numerical value like `null` or an empty string `''`. It'll make the row only fit it's elements rather than strictly adhere to the sections grid. 

Also `hide` and `show` are being deprecated in favor of more general style options in v4 to better support the configuration UI. I'm planning on completely replacing all the style options with an even more general styles field for CSS strings so I don't have to expose each subelement separately.

```yaml
features:
  - type: custom:service-call
    entries:
      - type: slider
        label: VALUE
        thumb: flat
        unit_of_measurement: '%'
        value_attribute: brightness
        tap_action:
          action: call-service
          service: light.turn_on
          data:
            brightness_pct: VALUE
            entity_id: light.sunroom_ceiling
    style:
      display: '{{ "none" if is_state("light.sunroom_ceiling", "off") else "initial" }}'
type: tile
entity: light.sunroom_ceiling
tap_action:
  action: toggle
layout_options:
  grid_columns: 4
  grid_rows: ''
```
