### ISSUE TITLE
Slider rendering issue

### ISSUE THREAD

**Issue by Xlinx64** [Nerwyn/service-call-tile-feature#34]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
3.3.8/4.0.0
**Last working release (if known):**
?
**Browser and Operating System:**
Firefox 128.0 MacOS 14.5

**Description of problem:**
The sliders are not rendered correctly on the right side. See screenshot:
![Bildschirmfoto 2024-07-10 um 11 08 05](https://github.com/Nerwyn/service-call-tile-feature/assets/14150988/78085a78-997d-4b95-b865-1a12edf3ca2e)

**Your Full Remote Config**

```yaml
type: custom:service-call
entries:
  - type: slider
    range:
      - 5
      - 30
    step: 0.5
    unit_of_measurement: ' °C'
    value_attribute: temperature
    label_style:
      font-size: 14px
      font-weight: 450
    tap_action:
      action: call-service
      service: climate.set_temperature
      target:
        entity_id: climate.klimaanlage
      data:
        temperature: VALUE

```
