### ISSUE TITLE
Add confirmation support for service call buttons

### ISSUE THREAD

**Issue by eth0up** [Nerwyn/service-call-tile-feature#4]
Some of my existing HA Buttons and Tiles use confirmations via `tap_action` to prevent accidental clicks/taps from executing actions. Some of these actions include reboot or activation of specific devices which could be potentially disruptive/dangerous if triggered at the wrong time. I rely on user confirmation to ensure that these actions aren't executed unintentionally.

![image](https://github.com/Nerwyn/service-call-tile-feature/assets/14995689/0fd8fb73-8dce-4724-8a28-ccca14f4201e)

(Partial YAML Config)
```
type: tile
entity: script.network_appliance_power_cycle
tap_action:
  action: call-service
  service: script.network_appliance_power_cycle
  target: {}
  confirmation:
    text: Power Cycle Appliance?
.......
```

I added the same `tap_action` configuration to a service call tile button which runs a script different from the Tile's target entity and found that the confirmation dialog was not displayed when clicking/tapping the button.

I'd like the ability to apply a confirmation to service call tile buttons similar to how `tap_action` works for HA Tiles and Buttons (https://www.home-assistant.io/dashboards/actions/)

Example HACS add-on using `tap_action`: https://github.com/benct/lovelace-multiple-entity-row/blob/168f25138458bc78f3c18401104a000dbbb4da41/src/index.js#L36
