### ISSUE TITLE
Variables/Custom fields support for scripts

### ISSUE THREAD

**Issue by justspacedog** [Nerwyn/service-call-tile-feature#40]
**Is your feature request related to a problem? Please describe.**
I have a script with a custom field (`mode`), I would like to call. I thought I can do so with

```
target:
  entity_id: script.luftfiltermodus
data:
  mode: strong
```

but then I will get the error `Failed to call service script/turn_on. extra keys not allowed @ data['modus"]`

I tired different versions, also like nested in `variables` or in `service_data`.

**Describe the solution you'd like**
I would like to call my script with variables I provide. My current working example is:

```
 - type: custom:mushroom-template-card
            layout: vertical
            icon: mdi:fan-speed-2
            tap_action:
              action: call-service
              service: script.turn_on
              service_data:
                entity_id: script.luftfiltermodus
                variables:
                  mode: strong
```

**Comment by Nerwyn** [comment]
Try using the script as the service instead of the target. AFAIK this should already work.

**Comment by justspacedog** [comment]
Then I’m getting the error `Failed to call service script/turn_on. must contain at least one of entity_id, device_id, area_id, floor_id, label_id.` even if there is an entity_id defined…

**Comment by Nerwyn** [comment]
Wait, your config says `custom:mushroom-template-card`. This isn't the mushroom repo.

**Comment by Nerwyn** [comment]
If that was a typo, your `tap_action` should be:

```yaml
action: call-service
service: script.luftfiltermodus
data:
  variables:
    mode: strong
```

**Comment by Nerwyn** [comment]
Can you also share your script? I haven't used scripts with input variables before and an example would help me debug if it is an issue with this repo.

**Comment by justspacedog** [comment]
Sorry for the confusion. The mushroom was just a working example, so with mushroom it works, with tile not. My script is

```
alias: Luftbefeuchtermodus
sequence:
  - service: humidifier.turn_on
    data:
      entity_id: humidifier.smartmi_humidifier_rainforest
  - service: select.select_option
    data:
      entity_id: select.smartmi_humidifier_rainforest_mode
      option: "{{ mode }}"
  - service: fan.turn_on
    data:
      entity_id: fan.smartmi_humidifier_rainforest_fan_homekit
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ mode == 'Sleep' }}"
        sequence:
          - service: fan.set_percentage
            data:
              entity_id: fan.smartmi_humidifier_rainforest_fan_homekit
              percentage: 16
          - service: fan.turn_off
            data:
              entity_id: fan.smartmi_humidifier_rainforest_fan_homekit
fields:
  mode:
    description: The mode to set for the air humidifier
    example: auto
description: ""

```

**Comment by justspacedog** [comment]
> If that was a typo, your `tap_action` should be:
> 
> ```yaml
> action: call-service
> service: script.luftfiltermodus
> data:
>   variables:
>     mode: strong
> ```

This doesn’t work. Service should be `script.turn_on` I think.

**Comment by Nerwyn** [comment]
This is working for me.

```yaml
type: button
tap_action:
  action: call-service
  service: script.turn_on
  target:
    entity_id: script.script_args_test
  data:
    variables:
      speed: 25
autofill_entity_id: false
```

Maybe it's because you're using deprecated field `service_data` instead of `data`?
