### ISSUE TITLE
Selector doesn't select

### ISSUE THREAD

**Issue by jherby2k** [Nerwyn/service-call-tile-feature#41]
**Checklist:**

- [ ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**

4.0.4

**Last working release (if known):**

N/A

**Browser and Operating System:**

Edge / Windows 11

**Description of problem:**

Not sure if this is just doc confusion or an actual bug, but i i set up a real simple selector here that isn't selecting anything. It highlights the current selection correctly - it just doesn't appear to actually change the selection when i click the buttons. Do we have to explicitly implement  `input_select.select_option` via tap_action? That's not clear in the readme - sounds like it should be implicit. All the examples do seem to implement it, but they're much more complicated than what i'm trying to do here.
```yaml
features:
  - type: vacuum-commands
    commands:
      - start_pause
      - locate
      - return_home
      - stop
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: select.valetudo_rosie_mode
        options:
          - option: vacuum_and_mop
            icon: mdi:water
          - option: vacuum
            icon: mdi:water-off
```

**Comment by jherby2k** [comment]
this seems to be the minimum working config:

```yaml
features:
  - type: vacuum-commands
    commands:
      - start_pause
      - locate
      - return_home
      - stop
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: select.valetudo_rosie_mode
        options:
          - option: vacuum_and_mop
            icon: mdi:water
            tap_action:
              action: call-service
              service: select.select_option
              data:
                option: vacuum_and_mop
              target:
                entity_id: select.valetudo_rosie_mode
          - option: vacuum
            icon: mdi:water-off
            tap_action:
              action: call-service
              service: select.select_option
              data:
                option: vacuum
              target:
                entity_id: select.valetudo_rosie_mode
```
