### ISSUE TITLE
Selector too optimistic when using confirmation

### ISSUE THREAD

**Issue by jensrossbach** [Nerwyn/service-call-tile-feature#53]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser

**Release with the issue:**
4.0.10

**Last working release (if known):**
n/a

**Browser and Operating System:**
Home Assistant companion app on iOS 18

**Description of problem:**
I have configured a tile card with a custom feature. The custom feature is a selector with two options to turn on and off a light. The 'off' option additionally has a confirmation. When the light is on and I press on the 'off' option, the confirmation dialog is shown (as expected) but in the same moment, the selector switches to the 'off' option. When I then cancel the confirmation dialog, the selector is on the 'off' option although the light is still on.

**Javascript errors shown in the web inspector (if applicable):**
n/a

**Your Full Card Config**

```yaml
type: tile
entity: light.my_light
icon_tap_action:
  action: more-info
features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: light.my_light
        options:
          - entity_id: light.my_light
            option: 'on'
            tap_action:
              action: perform-action
              perform_action: light.turn_on
              data: {}
              target:
                entity_id: light.my_light
            icon: mdi:lightbulb-on
          - entity_id: light.my_light
            option: 'off'
            tap_action:
              action: perform-action
              perform_action: light.turn_off
              data: {}
              target:
                entity_id: light.my_light
              confirmation:
                text: Really turn off?
            icon: mdi:power
```

**Additional information:**
n/a
