### ISSUE TITLE
Plain showing of entity states

### ISSUE THREAD

**Issue by DerOetzi** [Nerwyn/service-call-tile-feature#61]
**Is your feature request related to a problem? Please describe.**
I really like the possibilities of tile features because of the smooth layout the make possible. Using a vertical stack of cards to combine different entities for the same device leads optical to a division into several cards. 

![Bildschirmfoto_2024-11-11_08-28-17](https://github.com/user-attachments/assets/cb3e251a-ef3f-4690-bbe5-45e42afadecd)

I use the custom:multiple-entity-row as tile feature, which is only possible by editing inside the code editor at the moment and this is very buggy as well. So I would prefer using the visualeditor in the way how i can add sliders and buttons and so on, but with a visual editor to get a smooth one card layout like this:

![Bildschirmfoto_2024-11-11_08-19-45](https://github.com/user-attachments/assets/81a84f90-31d7-4940-a28b-dfcbaf70ec85)

**Describe the solution you'd like**
Add another custom feature type, which can be used to show additional entity states in one single tile card. Best would be if several entities per custom feature row can be shown (e. g. the Temperature row at the screenshot.) but although a single entity state per row would fine. 

**Describe alternatives you've considered**
As I wrote above I user custom:multiple-entity-row at the moment, but only can achieve with many hacks inside the code-editor.

And I although did an approach using your buttons without tap action.  But i'm not sure how to style them best.

![Bildschirmfoto_2024-11-11_09-40-56](https://github.com/user-attachments/assets/977aea25-f7a1-4510-b8b1-e9e906377cdf)

**Comment by Nerwyn** [comment]
I'm going to forego adding this as a custom feature, because as you said you can style buttons to get almost the same result.

![image](https://github.com/user-attachments/assets/75b43f69-704b-4e82-a346-eec027626c97)

```yaml
features:
  - type: custom:service-call
    entries:
      - type: button
        label: Temperature
        icon: mdi:thermometer
        styles: |-
          :host {
            flex-direction: row;
            flex-basis: 400%;
            justify-content: left;
            gap: 24px;
            margin-left: 12px;
          }
          .label {
            width: unset;
          }
        autofill_entity_id: false
      - type: button
        entity_id: sensor.downstairs_indoor_temperature
        styles: |-
          .icon {
            position: absolute;
          }
          .label {
            text-align: center;
            line-height: 40px;
          }
        label: |-
          Indoors
          {{ value }}{{unit}}
        unit_of_measurement: " °F"
        icon: mdi:home-floor-1
      - type: button
        entity_id: sensor.upstairs_thermostat_current_temperature
        styles: |-
          .icon {
            position: absolute;
          }
          .label {
            text-align: center;
            line-height: 40px;
          }
        label: |-
          Upstairs
          {{ value }}{{unit}}
        unit_of_measurement: " °F"
        icon: mdi:home-floor-2
      - type: button
        entity_id: sensor.downstairs_outdoor_temperature
        styles: |-
          .icon {
            position: absolute;
          }
          .label {
            text-align: center;
            line-height: 40px;
          }
        label: |-
          Outdoors
          {{ value }}{{unit}}
        unit_of_measurement: " °F"
        icon: mdi:pine-tree
    styles: |-
      :host {
        --color: transparent;
        --md-ripple-pressed-color: transparent;
        --md-ripple-hover-color: transparent;
        --feature-height: 60px;
      }
  - type: custom:service-call
    entries:
      - type: spinbox
        icon: mdi:thermometer
        label: "{{ value }}{{ unit }}"
        step: 1
        debounceTime: 1000
        range:
          - "{{ state_attr(\"climate.downstairs_thermostat\", \"min_temp\") }}"
          - "{{ state_attr(\"climate.downstairs_thermostat\", \"max_temp\") }}"
        value_attribute: temperature
        unit_of_measurement: °F
        hold_action:
          action: repeat
        entity_id: climate.downstairs_thermostat
        styles: |-
          :host {
            --background: var(--tile-color);
            --icon-color: var(--tile-color);
            flex-flow: row;
          }
        tap_action:
          action: call-service
          target:
            entity_id: climate.downstairs_thermostat
          service: climate.set_temperature
          data:
            temperature: "{{ value }}"
    styles: ""
  - type: custom:service-call
    entries:
      - type: button
        label: XKCD
        value_from_hass_delay: 5000
        momentary_end_action:
          action: url
          url_path: https://xkcd.com/{{ 1000 * hold_secs }}
        entity_id: climate.downstairs_thermostat
        value_attribute: state
  - type: custom:service-call
    entries:
      - type: button
        entity_id: sensor.cold_flu_index_today
        label: |-
          State Float
          {{ value }}
        value_attribute: state
        styles: ""
      - type: button
        entity_id: sensor.cold_flu_index_today
        label: |-
          State Float
          {{ value }}
        value_attribute: strep_index
        icon: ""
        styles: |-
          .background {
            --color: {{ "blue" if state_attr(config.entity, config.attribute) < 3 else "green" }};
          }
        tap_action:
          action: more-info
          target:
            entity_id: sensor.cold_flu_index_today
          confirmation:
            text: Show Cold & Flu Index?
            exemptions:
              - user: af773a442cd7493f8178f7c23b7882d7
              - user: 7e9bf9d73edc48df8ece5cec7e9a4f00
          data: {}
  - type: custom:service-call
    entries:
      - type: button
        entity_id: climate.downstairs_thermostat
        styles: ""
        autofill_entity_id: true
        xlabel: "{{ date.fromisocalendar(2012, 22, 4) }}"
        label: >-
          {{ (labels()[8] | label_name | label_entities)[4] | state_translated
          }}

          {{ is_state_attr("light.chandelier", "brightness", 255) }}

          {{ is_device_attr("light.chandelier", "brightness", 255) }}
        tap_action:
          action: eval
          eval: |-
            setInterval(() => {
              console.log(new Date())
            }, 1000);
type: tile
entity: climate.downstairs_thermostat
layout_options:
  grid_columns: 4
  grid_rows: 4
```
