### ISSUE TITLE
Use Slider to show %

### ISSUE THREAD

**Issue by cloudbr34k84** [Nerwyn/service-call-tile-feature#62]
Hey @Nerwyn 

I was wondering if you could help, is it possible to use the slider to show the battery percentage?

```yaml
type: tile
entity: binary_sensor.beaus_bedroom_ensuite_vanity_leak_detector_top_shelf_water_leak
name: " Top Shelf"
features:
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: sensor.beaus_bedroom_ensuite_vanity_leak_detector_top_shelf_battery
        range:
          - 0
          - 100
        tap_action:
          action: perform-action
          target:
            entity_id: >-
              binary_sensor.beaus_bedroom_ensuite_vanity_leak_detector_top_shelf_water_leak
          data: {}
        step: 1
        thumb: flat
        styles: |-
          :host {
            flex-flow: row;
          }
        label: Battery
        icon: mdi:battery
card_mod:
  style:
    ha-tile-info$: |
      .secondary:after {
        visibility: visible;
        content: " ⸱ {{ states('sensor.beaus_bedroom_ensuite_vanity_leak_detector_top_shelf_battery') }}%";
      }
```

**Comment by Nerwyn** [comment]
Questions like this are better suited for the discussions section and shouldn't be marked as bugs.

Set action to none to prevent touching the slider from doing anything, and then use a template for the label.

```yaml
type: tile
entity: binary_sensor.beaus_bedroom_ensuite_vanity_leak_detector_top_shelf_water_leak
name: " Top Shelf"
features:
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: sensor.beaus_bedroom_ensuite_vanity_leak_detector_top_shelf_battery
        range:
          - 0
          - 100
        tap_action:
          action: none
        step: 1
        thumb: flat
        styles: |-
          :host {
            flex-flow: row;
          }
          .icon {
            padding: 11px;
          }
          .label {
            padding-right: 42px;
          }
        label: '{{ value }}{{ unit }}'
        icon: mdi:battery
        unit_of_measurement: '%'
card_mod:
  style:
    ha-tile-info$: |
      .secondary:after {
        visibility: visible;
        content: " ⸱ {{ states('sensor.beaus_bedroom_ensuite_vanity_leak_detector_top_shelf_battery') }}%";
      }
```
