### ISSUE TITLE
Dropdown can't show state of select entity if is not present in options

### ISSUE THREAD

**Issue by martindybal** [Nerwyn/service-call-tile-feature#65]
**Checklist:**

- [ X ] I updated to the latest version available
- [ X ] I cleared the cache of my browser
- [ X ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
 CUSTOM-FEATURES-FOR-TILES-AND-MORE v4.2.1

**Last working release (if known):**

**Browser and Operating System:**
https://whatismybrowser.com/w/PSY6SCY

**Description of problem:**
Suppose we have a select.test that has the option [A, B, C]. And I want to add a dropdown that allows me to select A or B. I don't want to be able to select C (in my case it's technical transition state which cannot be selected).  With this configuration, the dropdown shows as empty if the select.test state is C. It is not possible to set custom text in it. Also the select.test C value is not displayed.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Card Config**

```yaml
type: tile
entity: light.test
features:
  - type: custom:service-call
    entries:
      - type: dropdown
        entity_id: select.test
        options:
          - entity_id: select.test
            option: A
            tap_action:
              action: perform-action
              perform_action: select.select_option
              data:
                option: A
              target:
                entity_id: select.test
          - entity_id: select.test
            option: B
            tap_action:
              action: perform-action
              perform_action: select.select_option
              data:
                option: B
              target:
                entity_id: select.test
```

**Additional information:**

**Comment by Nerwyn** [comment]
So you want to be able to dipslay the third option `C` but not have it show up in the dropdown options list? You can do that with CSS! Add this to the base CSS styles of your dropdown. You'll also have to add it as an option in your options list.

```css
.option:nth-child(3) {
  display: none;
}
```
