### ISSUE TITLE
Add switch toggle and checkbox feature

### ISSUE THREAD

**Issue by martindybal** [Nerwyn/service-call-tile-feature#66]
The default entity card has a nice switch control. It nicely guides the user how to switch and displays the status. However, I use a tile card throughout my dashboard and using the Entity card is not a good fit, it looks different. I would like the option to have the switch as an extension of the TileCard. Also a checkbox would be handy. For example when I choose which rooms to clean.

![image](https://github.com/user-attachments/assets/47644f1c-789c-4166-9417-ca80d7cc5cda)

**Comment by Nerwyn** [comment]
Not a bad idea! It'll be a while before I can get around to implementing this.

W3 schools has [a good guide](https://www.w3schools.com/howto/howto_css_switch.asp) on turning check boxes into toggles with CSS (I limit the usage of any HA or third party custom elements except `ha-icon` to limit the possibility of the custom features breaking with HA updates, except for in the editor which may break over time if I don't fix it).

Thinking through requirements:
- Style
  - Should support checkbox and toggle switch default styles, as they're functionally the same.
  - Material design 2 vs 3? Home Assistant uses MD2 but MD3 is more up to date and I'm partial to it a la [Material Rounded theme](https://github.com/Nerwyn/material-rounded-theme). Maybe implement both?
    - https://m2.material.io/components/checkboxes
    - https://m2.material.io/components/switches
    - https://m3.material.io/components/checkbox/overview
    - https://m3.material.io/components/switch/overview
  - One label.
  - Two icons.
    - The main icon to the left.
    - An icon on the checkbox or switch thumb, as described in the MD3 docs.
- Action
  - Supports a single tap action.
  - Include examples in README for how to use templates to change the action based on the toggle state.
- Internal value
  - Uses the normal `setValue` logic, but uses the boolean "truthiness" of that value to determine if feature is on or off.

**Comment by martindybal** [comment]
Great! Let me know if you need any help or feedback.

**Comment by lone-faerie** [comment]
Just came across this and wanted to share my way of doing a switch using the selector feature. Note, I'm using the Material You theme, so the exact style and colors might not be the same.

![Image](https://github.com/user-attachments/assets/b5436aab-419f-412d-9f6b-673b2275dd9e)

```yaml
features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: light.the_big_light
        options:
          - entity_id: light.the_big_light
            tap_action:
              action: perform-action
              perform_action: light.toggle
              target:
                entity_id:
                  - light.the_big_light
              data: {}
            option: "off"
            icon: "{% if not is_state(config.entity, 'on') %}mdi:power{% endif %}"
            styles: |-
              :host {
                {% if not is_state(config.entity, 'on') %}
                flex-basis: 133%;
                {% endif %}
                --color: var(--md-sys-color-surface-variant-dark);
                --icon-color: var(--md-sys-color-on-surface-variant-dark);
              }
          - entity_id: light.the_big_light
            option: "on"
            tap_action:
              action: perform-action
              perform_action: light.toggle
              target:
                entity_id:
                  - light.the_big_light
              data: {}
            styles: |-
              :host {
                {% if is_state(config.entity, 'on') %}
                flex-basis: 133%;
                {% endif %}
                --color: var(--md-sys-color-primary-dark);
                --icon-color: var(--md-sys-color-on-primary-dark);
              }
            icon: "{% if is_state(config.entity, 'on') %}mdi:power{% endif %}"
        styles: |-
          :host {
          {% if is_state(config.entity, 'on') %}
            --background: var(--md-sys-color-primary-dark);
          {% else %}
            --background: var(--md-sys-color-surface-variant-dark);
          {% endif %}
          }
        haptics: true
type: tile
vertical: false
entity: light.the_big_light
state_content: state
tap_action:
  action: toggle
hold_action:
  action: more-info
```

**Comment by martindybal** [comment]
@lone-faerie Great idea, thank you!

There is updated component to work with the default Home Assistant theme. 

![Image](https://github.com/user-attachments/assets/67e907fc-af3f-4400-87b0-d1f7b60d418a)

![Image](https://github.com/user-attachments/assets/1fb437b6-9a84-4cdb-aac7-b788e21f04bb)

```yaml
features:
  - type: custom:service-call
    entries:
      - type: selector
        entity_id: switch.garage_open_door_for_delivery
        options:
          - entity_id: switch.garage_open_door_for_delivery
            tap_action:
              action: perform-action
              perform_action: switch.turn_off
              target:
                entity_id:
                  - switch.garage_open_door_for_delivery
              data: {}
            option: "off"
            icon: ""
            styles: |-
              :host {
                flex-basis: 133%;
                --color: --disabled-color;
                border-radius: 0;
              }
          - entity_id: switch.garage_open_door_for_delivery
            option: "on"
            tap_action:
              action: perform-action
              perform_action: switch.turn_on
              target:
                entity_id:
                  - switch.garage_open_door_for_delivery
              data: {}
            icon: mdi:power
            styles: |-
              :host {
                --color: var(--state-switch-active-color);
                --icon-color: var(--primary-text-color);
              }
        styles: |-
          :host {
          {% if is_state(config.entity, 'on') %}
            --background: var(--state-switch-active-color);
          {% else %}
            --background: var(--state-switch-off-color);
          {% endif %}
          }
        haptics: true
type: tile
vertical: false
entity: switch.garage_open_door_for_delivery
state_content: state
tap_action:
  action: toggle
hold_action:
  action: more-info

```

**Comment by AuraHerreroRuiz** [comment]
Now with the [2025.3 update bringing the toggle feature](https://www.home-assistant.io/blog/2025/03/05/release-20253/#switch-toggle), I'd be delighted to have a more customasible version, and I believe it would be a better fit for a "toggle switch" with the design language of the other features like the selector, instead of using a material switch.

For example, something I'd like to customise is the icons. One nitpick I have with the current toggle feauture is that they use ⏻ for the "On" state, when it's really a "Go to stand-by" symbol [as per the IEC](https://www.iso.org/obp/ui#iec:grs:60417:5009), or perhaps a "toggle power" symbol. I know the meaning of ⏻  is less concrete now do to its cultural impact, but I'd rather if the switched used the [On ⏽ symbol](https://www.iso.org/obp/ui#iec:grs:60417:5007) for that state instead.

For now I have switched to the above custom selector with those icons, but I lose the switch animation, and I'd like to have it back.

For the checkboxes- perhaps that could be a different feature entirely, that maybe a separate issue. Something I see that would differentiate their functionality is the ability to group them in [parent-child](https://m3.material.io/components/checkbox/guidelines#26cbff1c-7a56-4237-b563-5593573e6cf4). Perhaps the feature could be a "multiple-choice selector" instead of a simple checkbox, I'd find that would cover more ground and be more intuitive. Those are my two cents, at least.

**Comment by Nerwyn** [comment]
The first 4.3.0 beta is out with customizable toggles. It looks and functions like the new Home Assistant default toggle and I haven't implemented the material design toggles and switches yet. I also haven't implemented the configuration UI but for now here's a simple YAML config you can paste in after adding it to a custom features row.

```yaml
type: toggle
entity_id: light.sunroom_ceiling
tap_action:
  action: toggle
  target:
    entity_id: light.sunroom_ceiling
  data: {}
icon: '{{ "mdi:ceiling-light" if checked else "mdi:ceiling-light-outline" }}'
label: '{{ value }}'
```

**Comment by Nerwyn** [comment]
I've implemented the checkbox toggle thumb variation in beta 3. It's functionally the same as the default toggle, just looks different. Adding additional functionality for use in a parent-child list or multiple checkboxes in one is not something I'm going to pursue, as it wouldn't fit well with Home Assistant actions.

**Comment by Nerwyn** [comment]
Beta 5 (beta 4 had a bug) changes:
- Material Design 2 toggle option.
- Separate icons for next to label and inside Material Design checkbox/switch thumb.

**Comment by Nerwyn** [comment]
Beta 8 changes:
- Material design 3 toggles!
  - Works best with (shameless plug) [Material You theme](https://github.com/Nerwyn/material-rounded-theme).
- Material design toggle color and icon size tweaks.

Here's the default toggle with all of the variations from this project.

![Image](https://github.com/user-attachments/assets/8a3645f0-27cc-448c-ad26-df2278559694)

**Comment by AuraHerreroRuiz** [comment]
I've been toying with the beta, and I really like it. Thanks so much for putting it together, and so quickly too!

I just have one caveat: There are some entities that do not have an "on" or "off" state but would benefit from a switch in some cases. For example, I have a climate entity, but it only has the "Off" and "heat" modes available, as it's just a water boiler. I'd really like to have a switch for it, with say the flame and flame-off icons, but I can't, not with just the feature.

I _can_ create a template switch that essentially turns the HVAC modes to a switch, but I'd like if I could template what the "On" and "Off" state means for the switch.

**Comment by lone-faerie** [comment]
I think a simple way of implementing that would be to allow custom "On" and "Off" values or a single "Checked" value, like the "Min" and "Max" for sliders and spinboxes. Changing the icon can already be done with templates. So for a climate entity, you could have a config like:
```yaml
type: toggle
entity_id: climate.hvac
checked: heat
tap_action:
  action: perform-action
  perform_action: '{{ "climate.set_hvac_mode" if checked else "climate.turn_off" }}'
  target:
    entity_id: climate.hvac
  data: '{{ dict(hvac_mode="heat") if checked else dict() }}'
icon: '{{ "mdi:flame" if checked else "mdi:flame-off" }}'
```

**Comment by Nerwyn** [comment]
I'm pretty hesitant to let users template the feature value, as that would require significant and confusing changes in logic to how values are retrieved from the hass object. Templating a sensor would be the right way to go about it and is what I tell people to do when they've asked for it as a feature in the past.

Allowing for additional checked on and off lists would be simpler to implement and I'm going to try that.

**Comment by Nerwyn** [comment]
I've added `checked_values` and `check_numeric` to the toggle options in 4.3.0-beta.011. You can now change (not add to) the list of possible checked value strings, and disable the checked numeric value comparison (default on).

**Comment by AuraHerreroRuiz** [comment]
I've tried using `checked_values`, and it works perfectly for my purposes! Also thanks @lone-faerie I was already templating the icon, but I missed that I could use "checked" instead of checking entity state.

**Comment by MathisP75** [comment]
I really like how customizable these toggles are, but I can't figure out how to change the color depending on the state.

**Comment by Nerwyn** [comment]
That should work for the default style toggle. The Material Design checkbox and switches have much more complicated CSS and use material design theme variables. I'll have to include them all in the README when I get around to updating it before release next week.

```css
/* Switches */
--switch-checked-button-color: var(--md-sys-color-on-primary);
--switch-unchecked-button-color: var(--md-sys-color-outline);
--md-switch-checked-track-color: var(--md-sys-color-primary);
--md-switch-unchecked-track-color: var(--md-sys-color-surface-container-highest);
--md-switch-checked-icon-color: var(--md-sys-color-on-primary-container);
--md-switch-unchecked-icon-color: var(--md-sys-color-surface-container-highest);
--md-switch-checked-button-state-layer: var(--md-sys-color-primary-container);
--md-switch-unchecked-button-state-layer: var(--md-sys-color-on-surface-variant);
--md-switch-unchecked-track-state-layer: var(--md-sys-color-on-surface);

/* Checkboxes */
--mdc-checkbox-checked-color: var(--md-sys-color-primary);
--mdc-checkbox-ink-color: var(--md-sys-color-on-primary);
--mdc-checkbox-unchecked-color: var(--md-sys-color-on-surface-variant);
--mdc-checkbox-unchecked-state-layer: var(--md-sys-color-on-surface);
```

**Comment by Nerwyn** [comment]
Beta 12 changes:

- Remove the legacy string interpolation system.
  - Was added in beta 11 but I forget to mention it.
  - The vast majority of people should be using templates instead.
- Add a toggle block list.
  - Allow: `true, yes, on, enable, enabled, 1`
  - Block: `false, no, off, disable, disabled, 0, undefined, null`
- Allow users to let toggles block a list of values rather than allow them.

**Comment by Nerwyn** [comment]
Beta 13 changes:
- Firefox fixes because Firefox has poor `:host` and `:has` support, especially when used together.
- Better handling of small width Material Design checkbox/switch toggle feature to hide label overflow instead of icon.

**Comment by Nerwyn** [comment]
Beta 14 changes:
- If a Material Design checkbox/switch has no separate icon or label, then it's CSS `flex` is set to `0 0 min-content`, which causes it to only be as wide as necessary to fit the toggle.
  - You can override this with user CSS styles, but I think it works better this way.
- Removed `thumb_icon` in favor of `checked_icon` and `unchecked_icon`, so users don't have to template state icons for different checked/unchecked conditions.
  - Not that templating the icon was difficult, but it caused an unpleasant display change issue when used with the default toggle.
- Added checked/unchecked icons to default toggle, where they'll appear in the background.
  - Like in [this Home Assistant documentation screenshot](https://www.home-assistant.io/dashboards/features/#toggle) which appears to show an unreleased version of the toggle with an additional icon.

**Comment by Nerwyn** [comment]
Beta 16: rtl language fixes.

I've also updated the README with toggle information and screenshots. With that it should be release ready. Let me know if there's any more feedback over the next day or so before then! @martindybal I'm not sure if you've seen/tried the beta yet.

**Comment by Nerwyn** [comment]
[Released 4.3.0.](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/4.3.0)

**Comment by dnestico** [comment]
Is there any way to fix the spacing? Looks a little weird because of it.
<img width="484" alt="Image" src="https://github.com/user-attachments/assets/55b091e4-e802-4505-869d-409fafef68c2" />

Here's the M3 component screenshot where there's no awkward gap
<img width="470" alt="Image" src="https://github.com/user-attachments/assets/4b987882-daf7-4813-8410-415d5868d3fa" />

**Comment by Nerwyn** [comment]
The simplest fix is to add an empty label. That would trick the standalone Material Design checkbox/switch into not using the `flex: 0 0 min-content` style. You could also add this to the overall row styles for a more "proper" fix:

```css
.row {
  justify-content: flex-end;
}
```

**Comment by dnestico** [comment]
That fixed it, thanks! now to figure out making the feature work with auto-entities.

<img width="468" alt="Image" src="https://github.com/user-attachments/assets/048b5b2c-299f-4cbf-8e79-a8a57f46933a" />

**Comment by martindybal** [comment]
@Nerwyn thanks! Thanks! This has improved my dashboard a little bit again.

**Comment by martindybal** [comment]
@dnestico you can use card_mod to fix this

```css
.content {
    padding-right: 0!important;
}

hui-card-features {
  max-width: 60px!important;
}
```
