### ISSUE TITLE
Templating doesn't work with the states objects

### ISSUE THREAD

**Issue by fallingcats** [Nerwyn/service-call-tile-feature#70]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:** 2024.12 / 4.2.2

**Last working release (if known):**

**Browser and Operating System:**
Firefox on Arch Linux

**Description of problem:**

Templates that use the states object directly don't seem to render

**Javascript errors shown in the web inspector (if applicable):**
```
None applicable
```

**Your Full Card Config**

```yaml
type: tile
entity: switch.doorlock
features:
  - type: custom:service-call
    entries:
      - type: button
        entity_id: switch.doorlock
        label: >-
          {{ state_translated("binary_sensor.ikea_of_sweden_parasoll_door_window_sensor_opening") }}
          {{ states.binary_sensor.ikea_of_sweden_parasoll_door_window_sensor_opening.last_changed | time_since }}
          ago
```

Should render as `Closed 2 hours ago` but actually renders as `Closed  ago`

If I simplify the template to `a {{ states["binary_sensor.ikea_of_sweden_parasoll_door_window_sensor_opening"].state }} b` it renders as `a b` when dev tools gives me `a off b`

**Additional information:**
