### ISSUE TITLE
Sliders don't start at the very left

### ISSUE THREAD

**Issue by jensrossbach** [Nerwyn/service-call-tile-feature#76]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.2.2
**Last working release (if known):**

**Browser and Operating System:**
Windows 11 + Edge / iOS + Companion app

**Description of problem:**
I created a slider to use as progress bar for media playback derived from the example in the README of the repository. When a song starts, the slider does not begin at the very left but instead approximately 15 pixels from the left:

![image](https://github.com/user-attachments/assets/fb12aa6e-84b7-4740-85b2-de9a5717a642)
If I use a round thumb instead of the flat thumb, it is even worse.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Card Config**

```yaml
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: media_player.arbeitszimmer
        tap_action:
          action: perform-action
          perform_action: media_player.media_seek
          data:
            seek_position: "{{ value }}"
          target:
            entity_id: media_player.arbeitszimmer
        value_attribute: media_position
        value_from_hass_delay: 5000
        range:
          - 0
          - "{{ state_attr(config.entity, 'media_duration') }}"
        step: 1
        thumb: flat
        styles: |-
          :host
          {
            --color: var(--control-slider-color);
            flex-basis: 300%;
            height: 20px;
          }
      - type: button
        entity_id: media_player.arbeitszimmer
        icon: mdi:play-pause
        tap_action:
          action: perform-action
          perform_action: media_player.media_play_pause
          target:
            entity_id:
              - media_player.arbeitszimmer
          data: {}
      - type: button
        entity_id: media_player.arbeitszimmer
        icon: mdi:skip-previous
        tap_action:
          action: perform-action
          perform_action: media_player.media_previous_track
          target:
            entity_id:
              - media_player.arbeitszimmer
          data: {}
      - type: button
        entity_id: media_player.arbeitszimmer
        icon: mdi:skip-next
        tap_action:
          action: perform-action
          perform_action: media_player.media_next_track
          target:
            entity_id:
              - media_player.arbeitszimmer
          data: {}
```

**Additional information:**
