### ISSUE TITLE
Derive entity ID from parent level of tile card

### ISSUE THREAD

**Issue by jensrossbach** [Nerwyn/service-call-tile-feature#77]
**Is your feature request related to a problem? Please describe.**
I have to repeat the same entity ID a lot of times when it is required at several places, for example:

```yaml
features:
  - type: media-player-volume-slider
  - type: custom:service-call
    entries:
      - type: slider
        entity_id: media_player.arbeitszimmer
        tap_action:
          action: perform-action
          perform_action: media_player.media_seek
          data:
            seek_position: "{{ value }}"
          target:
            entity_id: media_player.arbeitszimmer
        value_attribute: media_position
        value_from_hass_delay: 5000
        range:
          - 0
          - "{{ state_attr(config.entity, 'media_duration') }}"
        step: 1
        thumb: flat
        styles: |-
          :host
          {
            --color: var(--control-slider-color);
            flex-basis: 300%;
            height: 20px;
          }
      - type: button
        entity_id: media_player.arbeitszimmer
        icon: mdi:play-pause
        tap_action:
          action: perform-action
          perform_action: media_player.media_play_pause
          target:
            entity_id:
              - media_player.arbeitszimmer
          data: {}
      - type: button
        entity_id: media_player.arbeitszimmer
        icon: mdi:skip-previous
        tap_action:
          action: perform-action
          perform_action: media_player.media_previous_track
          target:
            entity_id:
              - media_player.arbeitszimmer
          data: {}
      - type: button
        entity_id: media_player.arbeitszimmer
        icon: mdi:skip-next
        tap_action:
          action: perform-action
          perform_action: media_player.media_next_track
          target:
            entity_id:
              - media_player.arbeitszimmer
          data: {}
type: tile
entity: media_player.arbeitszimmer
icon_tap_action:
  action: toggle
grid_options:
  columns: 12
  rows: 2
state_content:
  - media_title
  - media_artist
show_entity_picture: true
```

**Describe the solution you'd like**
Entity IDs should be derived from parent levels up to the tile card level. So if I omit an entity ID at a specific place where it is required, it takes the entity from the parent level (or parent of parent and so on).

**Describe alternatives you've considered**
None

**Additional context**
None
