### ISSUE TITLE
JavaScript Error - Timer / Slider

### ISSUE THREAD

**Issue by baxgit** [Nerwyn/service-call-tile-feature#78]
**Checklist:**

- [X ] I updated to the latest version available
- [X ] I cleared the cache of my browser
- [X ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.2.3
**Last working release (if known):**

**Browser and Operating System:**
Browsers: Microsoft Edge, Google Chrome; OS: Windows 11

**Description of problem:**
I'd previously noticed some performance issues with dashboard pages that contained the service-call tile card but had largely ignored them. However, yesterday I noticed my browser was throwing a JavaScript error that appears to come from the card (see below). Whilst investigating the error I noticed it was continuously being thrown, literally hundreds of times, and as the volume grew the performance of the page started to degrade. I've narrowed down the issue to cards containing a timer slider per the YAML below. I copied this YAML directly from the GitHub example 7. 

**Javascript errors shown in the web inspector (if applicable):**
custom-features-row.min.js?hacstag=698501153423:2  Uncaught (in promise) Template render error: (unknown path)
  Error: Result returned NaN.
    at e._prettifyError (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:2526)
    at http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:41965
    at e.root [as rootRenderFunc] (eval at n._compile (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:42599), <anonymous>:17:3)
    at n.render (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:41887)
    at n.renderString (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:39931)
    at Nn (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:154168)
    at c.renderTemplate (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:101740)
    at c.buildLabel (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:103317)
    at c.render (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:168691)
    at c.update (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:162838)
custom-features-row.min.js?hacstag=698501153423:2  Uncaught (in promise) Template render error: (unknown path)
  Error: Result returned NaN.
    at e._prettifyError (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:2526)
    at http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:41965
    at e.root [as rootRenderFunc] (eval at n._compile (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:42599), <anonymous>:17:3)
    at n.render (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:41887)
    at n.renderString (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:39931)
    at Nn (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:154168)
    at c.renderTemplate (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:101740)
    at c.buildLabel (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:103317)
    at c.render (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:168691)
    at c.update (http://homeassistant.local:8123/hacsfiles/service-call-tile-feature/custom-features-row.min.js?hacstag=698501153423:2:162838)

```

```

**Your Full Card Config**

```yaml
features:
  - type: custom:service-call
    entries:
      - type: button
        label: "{{value}}"
        styles: |-
          :host {
            overflow: visible;
            height: 12px;
            border-radius: 0px;
            --color: none;
          }
        entity_id: sensor.aga_auto_off_time_remaining
      - type: slider
        tap_action:
          action: none
        value_attribute: elapsed
        thumb: flat
        step: 1
        range:
          - 0
          - >-
            {% set hms = state_attr(config.entity, "duration").split(":") %} {{
            (hms[0] |int ) * 3600 + (hms[1] | int) * 60 + (hms[2] | int) }}
        styles: |-
          :host {
            flex-basis: 1200%;
            height: 10px;
            --thumb-width: 1px;
            --color: green;
          }
        entity_id: timer.aga_auto_off_countdown_timer
      - type: button
        value_attribute: finishes_at
        label: "{{as_datetime(value).strftime('%-I:%M %p')}}"
        styles: |-
          :host {
            overflow: visible;
            height: 12px;
            border-radius: 0px;
            --color: none;
          }
        entity_id: timer.aga_auto_off_countdown_timer
    styles: |-
      .row {
        padding-bottom: 12px !important;
        padding-right: 12px !important;
        padding-left: 12px !important;  
      }  
type: tile
entity: input_text.aga_automation_status
name: Automation
grid_options:
  columns: 12
  rows: ""
icon_tap_action:
  action: perform-action
  perform_action: automation.toggle
  target:
    entity_id: automation.aga_activate_deactivate
icon: mdi:robot

```

**Additional information:**
