### ISSUE TITLE
Allow "null"/undefined option in Selectors

### ISSUE THREAD

**Issue by flavioxavier** [Nerwyn/service-call-tile-feature#79]
Sometimes I want to use an attribute that has 2 options plus is null (like `color_mode` in `lights` that can be `color_temp`, `xy` or just `null`that shows that the light is off, and right now there is no way to nightlight if the off/null/undefined option.

A way to implement would be just a check box in the option to say this on is for null/undefined values.

or just changing this check to allow empty sting or null string: [https://github.com/Nerwyn/service-call-tile-feature/blob/cd707dbd17ed877d0346ab8d536f00b9ba1b0f20/src/classes/custom-feature-selector.ts#L53C5-L53C67 #](https://github.com/Nerwyn/service-call-tile-feature/blob/cd707dbd17ed877d0346ab8d536f00b9ba1b0f20/src/classes/custom-feature-selector.ts#L53C5-L53C67)

```javascript

if (
    this.value == undefined && (optionName ?? '').toString() == ''  // or (optionName ?? '').toString() == 'null'
||
   this.value != undefined &&
   (this.value ?? '').toString() == (optionName ?? '').toString()
) {
 optionClass = 'selected-option';
}

Note that I haven’t test it

**Comment by Nerwyn** [comment]
You can probably do this with templates.

See [this example](https://github.com/Nerwyn/service-call-tile-feature?tab=readme-ov-file#example-2), specifically the dropdown options and value attribute.

```yaml
- type: dropdown
  entity_id: light.chandelier
  options:
    - entity_id: light.chandelier
      option: 255,166,87
      tap_action:
        action: perform-action
        perform_action: light.turn_on
        target:
          entity_id: light.chandelier
        data:
          brightness_pct: 100
          kelvin: 2000
      icon: mdi:checkbox-blank-circle
      styles: |-
        .icon {
          color: rgb(255,166,87);
        }
    - entity_id: light.chandelier
      option: 255,0,0
      tap_action:
        action: perform-action
        perform_action: light.turn_on
        target:
          entity_id:
            - light.chandelier
        data:
          brightness_pct: 100
          color_name: red
        confirmation: true
      icon: mdi:checkbox-blank-circle
      styles: |-
        .icon {
          color: var(--red-color);
        }
    - entity_id: light.chandelier
      option: 0,128,0
      tap_action:
        action: perform-action
        perform_action: light.turn_on
        target:
          entity_id:
            - light.chandelier
        data:
          brightness_pct: 100
          color_name: green
        confirmation: false
      icon: mdi:checkbox-blank-circle
      styles: |-
        .icon {
          color: var(--green-color);
        }
    - entity_id: light.chandelier
      option: 0,0,255
      tap_action:
        action: perform-action
        perform_action: light.turn_on
        target:
          entity_id:
            - light.chandelier
        data:
          brightness_pct: 100
          color_name: blue
      icon: mdi:checkbox-blank-circle
      styles: |-
        .icon {
          color: var(--blue-color);
        }
    - entity_id: light.chandelier
      option: 128,0,128
      tap_action:
        action: perform-action
        perform_action: light.turn_on
        target:
          entity_id:
            - light.chandelier
        data:
          rgb_color:
            - 128
            - 0
            - 128
          brightness_pct: 100
      icon: mdi:checkbox-blank-circle
      styles: |-
        .icon {
          color: var(--purple-color);
        }
    - entity_id: light.chandelier
      tap_action:
        action: perform-action
        perform_action: light.turn_off
        target:
          entity_id:
            - light.chandelier
        data: {}
      icon: mdi:checkbox-blank-circle-outline
      styles: ''
      option: 'off'
  value_attribute: '{{- "rgb_color" if is_state(config.entity, "on") else "state" }}'
  styles: |-
    .option {
      min-width: 0;
    }
```

You can improve this value attribute to check the color mode attribute and use it if not null.

```
{%- set color_mode = state_attr("light.sunroom_ceiling", "color_mode") -%}
{{- color_mode if color_mode != None else "state" -}}
```
