### ISSUE TITLE
Swiping off of feature with momentary actions does not trigger end behavior

### ISSUE THREAD

**Issue by Roliga** [Nerwyn/service-call-tile-feature#80]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.2.3

**Browser and Operating System:**
Multiple: Firefox (Windows, Linux), Home Assistant app (Android)

**Description of problem:**
Pressing down on a feature with start/end momentary behavior triggers the start behavior, but if the cursor is moved outside the feature while being held the end behavior is not triggered.

This applies both when using mouse or touch, where it's easy to accidentally trigger this issue while swipe scrolling.

Both start and end behavior are triggered if the cursor remains within the feature for the duration of the press.

Bellow is a configuration that opens a cover while a button is pressed, then stops when released.

**Your Full Card Config**

```yaml
features:
  - type: custom:service-call
    entries:
      - type: button
        momentary_end_action:
          action: perform-action
          perform_action: cover.stop_cover
          target:
            entity_id:
              - cover.some_cover
          data: {}
        momentary_start_action:
          action: perform-action
          perform_action: cover.open_cover
          target:
            entity_id:
              - cover.some_cover
          data: {}
type: tile
entity: cover.some_cover
```
