### ISSUE TITLE
Issue with Action Confirmation Text Theming

### ISSUE THREAD

**Issue by snakeeyes5** [Nerwyn/service-call-tile-feature#89]
**Checklist:**

- [X ] I updated to the latest version available
- [ X] I cleared the cache of my browser
- [ X] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:** Latest

**Last working release (if known):** N/A

**Browser and Operating System:** Windows/Chrome

**Description of problem:**

I use "confirmation" and "text" in my actions, example:

```
tap_action:
  action: perform-action
  perform_action: input_button.press
  target:
    entity_id: input_button.reset_kodi_master_bedroom
  confirmation:
    text: Reset Family Room Kodi
```

Works fine in a standard Tile action and I get this:

![Image](https://github.com/user-attachments/assets/371d48d0-5792-4f41-907f-20c45eeaaec2)

However, when I use it as an action in the tiles using this config:

```
features:
  - type: custom:service-call
    entries:
      - type: button
        entity_id: input_button.reset_kodi_master_bedroom
        tap_action:
          action: perform-action
          perform_action: input_button.press
          target:
            entity_id: input_button.reset_kodi_master_bedroom
          confirmation:
            text: Reset Family Room Kodi
          data: {}
        label: Test
type: tile
entity: input_button.reset_kodi_master_bedroom
tap_action:
  action: perform-action
  perform_action: input_button.press
  target:
    entity_id: input_button.reset_kodi_master_bedroom
  confirmation:
    text: Reset Family Room Kodi
```

I get this the default chrome yes/no:

![Image](https://github.com/user-attachments/assets/1caa9986-f4c8-4cf9-87dd-d5dbf8d69636)
