### ISSUE TITLE
Hidden state and other ideas

### ISSUE THREAD

**Issue by pathofleastresistor** [Nerwyn/service-call-tile-feature#9]
I've been playing around with this and it's pretty great. Congrats on building this. I realized that a project I was working on is really possible to replace with the tile card and this.

Some ideas to consider here:

- Hide on state - for example hide a feature if the main tile state is off
- Touchpad - I know you got it for your remote card, so adding a touchpad feature could allow for using the touchpad for non-remote use cases

**Comment by Nerwyn** [comment]
> Hide on state

- Should be possible to implement by applying `display: none` to the root styles.
  -  For individual features, use the style option and a template that sets display to `none` or `unset` depending on an `if is_state()` call.
  - For maximum customizability, should be something like a boolean named `hide_feature` which can be defined using a template.

> Touchpad

- This is a bit out of scope since the touchpad is a navigation element and it doesn't really make sense to add to as a tile feature.
- BUT if you really want to you can abuse this hidden feature/bug to add custom cards as tile features:
```yaml
features:
  - type: custom:android-tv-card
    rows:
      - - touchpad
type: tile
entity: remote.google_tv
show_entity_picture: false
vertical: false
```

**Comment by Nerwyn** [comment]
- `hide` added in [3.0.8](https://github.com/Nerwyn/service-call-tile-feature/releases/tag/3.0.8)
```yaml
features:
  - type: custom:service-call
    entries:
      - type: selector
        options:
          - option: A
            icon: mdi:alpha-a
            style:
              '--icon-color': >-
                {{ "var(--disabled-color)" if
                is_state("input_select.test_select", "A") }}
              '--color': var(--red-color)
          - option: B
            icon: mdi:alpha-b
            style:
              '--icon-color': >-
                {{ "var(--disabled-color)" if
                is_state("input_select.test_select", "B") }}
              '--color': var(--green-color)
          - option: C
            icon: mdi:alpha-c
            style:
              '--icon-color': >-
                {{ "var(--disabled-color)" if
                is_state("input_select.test_select", "C") }}
              '--color': var(--blue-color)
  - type: custom:service-call
    hide: '{{ is_state("input_select.test_select", "C") }}'
    entries:
      - type: slider
        entity_id: input_number.slider_test
        label: VALUE
        style:
          '--label-color': var(--disabled-color)
type: tile
entity: input_select.test_select
show_entity_picture: false
vertical: false
color: accent
```

**Comment by pathofleastresistor** [comment]
Thanks! Just clarifying that for my "hide" use case I'm styling it as `visibility: hidden` so it acts more as a spacer. But the hide state you added is another awesome addition.

**Comment by Aasikki** [comment]
Is the hide option still around? Just tried it and can't seem to get it to work. Not sure if it's me not understanding how to use it of it the feature is broken or removed.

I tried it like this, according to the snippet you posted.
```
type: tile
entity: media_player.living_room_entertainment
features_position: bottom
vertical: false
grid_options:
  columns: 12
  rows: 1
features:
  - type: custom:service-call
    hide: '{{ is_state("media_player.living_room_tv", "off") }}'
    entries:
      - type: selector
        entity_id: sensor.outdoor_temperature_feels_like
        options: []
```

But the hiding doesn't work and instead when I reopen the card editor I see that my template is now messed up after saving the card
```
type: tile
entity: media_player.living_room_entertainment
features_position: bottom
vertical: false
grid_options:
  columns: 12
  rows: 1
features:
  - type: custom:service-call
    hide: "{{ is_state(\"media_player.living_room_tv\", \"off\") }}"
    entries:
      - type: selector
        entity_id: sensor.outdoor_temperature_feels_like
        options: []
```

The template I used works fine in ha developer tools.

**Comment by Nerwyn** [comment]
It was removed in favor of pure css. Use the styles field (and the GUI editor) instead.

```css
{% if is_state(\"media_player.living_room_tv\", \"off\") %}
:host {
  display: none;
}
{% endif %}
```
