### ISSUE TITLE
Standalone Custom Feature Row card

### ISSUE THREAD

**Issue by DerOetzi** [Nerwyn/service-call-tile-feature#91]
**Is your feature request related to a problem? Please describe.**
I really like the selectors and sliders of custom feature cards, as their design is optimized for mobile usage. However, the fact that they can only be used in combination with a tile card sometimes takes up too much space:

![Image](https://github.com/user-attachments/assets/b1160278-b739-4dac-82f0-e82437c8507d)

For example, in the image, the selector at the bottom toggles the visibility of two cards above—one displaying daily and the other hourly forecast diagrams. Since this functionality is clearly linked to the cards above, the heading "Vorhersage" from the tile card becomes unnecessary and consumes valuable space.

**Describe the solution you'd like**
I would love to add custom feature rows without requiring a tile card—perhaps with a dedicated wrapper card for the custom feature row.

**Describe alternatives you've considered**
Another option could be the ability to hide all elements of the tile card.

**Comment by Nerwyn** [comment]
This project is for custom card features, not for modifying tile cards. Creating a new card type or modifying tile cards is completely out of scope.

You can use card-mod and the style options in this card to make the tile.

```css
card_mod:
  style: |
    .container {
      padding-top: 10px !important;
    }
    .content {
      display: none !important;
    }
```

**Comment by DerOetzi** [comment]
Thanks for reply

**Comment by DerOetzi** [comment]
I tried your solution and had to add the definition for ha-card height. Just if anyone find this solution


```css
card_mod:
  style: |
    ha-card: {
        height: auto !important;
    }
    .container {
      padding-top: 10px !important;
    }
    .content {
      display: none !important;
    }

```

![Image](https://github.com/user-attachments/assets/3a5abc6c-b8bf-43da-82a0-b5d1d522bda6)
