### ISSUE TITLE
Readonly slider opening entity details to use them as bar chart

### ISSUE THREAD

**Issue by DerOetzi** [Nerwyn/service-call-tile-feature#92]
**Is your feature request related to a problem? Please describe.**
To maintain a consistent look and feel across my dashboards, I want to use sliders as bar charts to display pollen count.

![Image](https://github.com/user-attachments/assets/f27c05a1-f1d6-4e9b-875b-445f660a5e18)

This works well, but there is one issue: Unless you set slider → interaction to None, the slider is not truly read-only. However, I want it to be clickable to trigger an interaction (e.g., "show details view") without causing a brief value change.

**Describe the solution you'd like**
A slider with a read-only option that prevents any value change when touched.

**Describe alternatives you've considered**
You can see the small i buttons behind each slider

**Comment by Nerwyn** [comment]
The sliders are heavily styled HTML input range elements, they can't have separate tap actions.

Instead, just style the buttons to overlay with the sliders.

```css
:host {
  position: absolute;
  left: calc(0.5 * var(--feature-padding));
  width: calc(100% - var(--feature-padding));
  border-radius: 100px;
  --color: transparent;
}
```
