### ISSUE TITLE
Support undefined options for Dropdowns and Selectors

### ISSUE THREAD

**Issue by andornaut** [Nerwyn/service-call-tile-feature#94]
**Is your feature request related to a problem? Please describe.**
Support `undefined` values as `option:` for Dropdowns and Selectors.

**Describe the solution you'd like**

Treat options that don't define an `option:` property as `option: <undefined>` and select and highlight these when the state attribute is undefined.

```yaml
- type: dropdown
  entity_id: media_player.living_room_tv
  value_attribute: source
  options:
    - label: Home
    - label: Receiver
      option: AV Receiver
    - label: Xbox
      option: Xbox
```

When the "Home" dropdown item is selected, the TV switches to the Android TV home screen (in my case, Projectivy launcher), which is not actually a "source" and therefore the `source` attribute is `undefined`. 

All other dropdown options are real sources, and so they're properly selected when the source is changed.

In the above, since the "Home" option does not define an "option" property, it is selected when the `source` state attribute is `undefined`.

Selectors should ideally work the same way.

**Describe alternatives you've considered**
I'm aware of [using templates to work around](https://github.com/Nerwyn/service-call-tile-feature/issues/79) the lack of this feature for Selectors, ~~but that doesn't appear to work for my Dropdown~~:

Oops, there was a bug in my `value_attribute` template. I'll leave this open in case you want to consider it, as I think the solution suggested above is more intuitive.
