### ISSUE TITLE
Inconsistent horizontal margin in md2-switch causes layout shifting with other features

### ISSUE THREAD

**Issue by martindybal** [Nerwyn/service-call-tile-feature#99]
**Checklist:**

- [X] I updated to the latest version available
- [X] I cleared the cache of my browser
- [X] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
 CUSTOM-FEATURES-FOR-TILES-AND-MORE v4.3.0

**Last working release (if known):**
It's new feature

**Browser and Operating System:**
https://whatismybrowser.com/w/KJ45FSA

**Description of problem:**
md2-switch has horizontal margin of 12px, while other features do not. This causes layout swapping in combination with the other features. Whether custom or default.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Card Config**

```yaml
type: tile
entity: light.103_night_light
grid_options:
  columns: 24
features_position: inline
features:
  - type: custom:service-call
    entries:
      - type: toggle
        entity_id: light.103_night_light
        tap_action:
          action: toggle
          target:
            entity_id: light.103_night_light
          data: {}
        haptics: true
        thumb: md2-switch
    styles: |-
      .row {
        justify-content: end;
      }
```

**Additional information:**

`.md2-switch` has `margin: calc((var(--feature-height, 40px) - 14px) / 2) 12px;`. 

![Image](https://github.com/user-attachments/assets/65f772cf-3ad3-4e00-86a9-b25677eb45c8)

<img width="251" alt="Image" src="https://github.com/user-attachments/assets/861a621b-51fe-43a1-ba62-f25a6d464c6c" />

![Image](https://github.com/user-attachments/assets/58583cbf-3488-43a5-b539-e42dee2aaf11)
